JMRI/EngineDriver

src/jmri/enginedriver/threaded_application.java

Added names to a few TA threads for easier debugging.

TA thread names

---

changelog-and-todo-list.txt

Robin, please accept this pull request to test your setup.

small change to test eclipse git setup

---

res/values/bool.xml
res/values/strings.xml
res/xml/preferences.xml
src/jmri/enginedriver/routes.java
src/jmri/enginedriver/throttle.java
src/jmri/enginedriver/turnouts.java

Two new preferences to control whether swiping (flinging) screens
rotates through the Turnouts Screen or the Routes Screen.

Added screen swiping prefs

---

.idea/misc.xml
res/values/strings.xml
res/xml/preferences.xml
src/jmri/enginedriver/throttle.java

AndroidStudio modified misc.xml (not me). 
I don't know if the change needs to be included or not.
I also added a few line breaks to get rid of some warnings.
Peter

fix - missing code for the 'increase Web View size' preference

---

.idea/misc.xml
assets/about_page.html
changelog-and-todo-list.txt
res/values/strings.xml
src/jmri/enginedriver/throttle.java

plus a few warnings from Android Studio

change "Web" option to "MRC Settings" when attached to MRCWifi

---

src/jmri/enginedriver/throttle.java

Direction Change not moving - unticking the preference had no effect

Fix - Direction Change while moving -ticking the preference had no effect

---

AndroidManifest.xml
assets/about_page.html
changelog-and-todo-list.txt
res/xml/preferences.xml
src/jmri/enginedriver/message_type.java
src/jmri/enginedriver/threaded_application.java

prevent newlines in text preferences

publish bugfix 2.14.1 to Play Store

---

res/values/arrays.xml
res/values/strings.xml
res/xml/preferences.xml
src/jmri/enginedriver/throttle.java

Option to show or hide the web view on a swipe up on the throttle page.

Experimental - Swipe to show/hide Web View + Game Pad support

---

assets/about_page.html
changelog-and-todo-list.txt
res/values/strings.xml
src/jmri/enginedriver/message_type.java
src/jmri/enginedriver/threaded_application.java
src/jmri/enginedriver/throttle.java

avoid several crashes reported to Play Store

---

assets/about_page.html
src/jmri/enginedriver/threaded_application.java
src/jmri/enginedriver/throttle.java

handle (ignore) more garbled incoming message data

avoid concurrentModification error reported to Play Store

---

EngineDriver.iml
res/values/arrays.xml
res/values/integers.xml
src/jmri/enginedriver/throttle.java

- Addition of keyboard support for precise setting of the throttle by key  '='+digit+digit+digit
- Addition of keyboard support for setting of all 28 function keys '-'+digit+digit
- Simplification of the Gamepad/keyboard code and options.

Gamepad & Keyboard support

---

res/values/bool.xml
res/values/strings.xml
res/xml/preferences.xml
src/jmri/enginedriver/throttle.java

Reduce redundant function calls.  Encapsulate preference handling to
ensure uniform behavior. Improve code clarity.  Added new separate
LocoSelectWhenMoving preference.  Slider limitJump handling stops when
target is reached.

Throttle cleanup and new pref

---

res/values/arrays.xml
src/jmri/enginedriver/throttle.java

Use correct speed set function in EStop.  Correct one Up code for
iCadeDpad.

Gamepad corrections

---

AndroidManifest.xml
res/values/arrays.xml
res/values/strings.xml
res/xml/preferences.xml
src/jmri/enginedriver/throttle.java

- option to lock the throttle screen on swipe up
- option to dim the screen (system wide) on swipe up
- preference of the dim screen brightness level

Experimental

---

res/values/arrays.xml
src/jmri/enginedriver/throttle.java

Changed "MKT" gamepad preference choices to "MTK"

Corrected name of MTK gamepad option

---

res/values/arrays.xml
res/values/strings.xml
res/xml/preferences.xml

Created SubScreens under Throttle Page Appearance Preferences for
"Slider Preferences", "Web View Preferences" and "Gamepad Preferences"
to declutter the display.  Edited/updated wording of some preference
text.

Preference Grouping

---

src/jmri/enginedriver/throttle.java

fix - correct the code to match the name changes in the preferences for swipe up.

fix - correct the code to match the name changes in the preferences for swipe up.

---

src/jmri/enginedriver/throttle.java

Refactored for readability, no functional changes

Minor Gamepad refactoring

---

AndroidManifest.xml
bin/AndroidManifest.xml
res/layout/consist_lights.xml
res/layout/consist_lights_item.xml
res/menu/consist_lights_edit_menu.xml
res/menu/throttle_menu.xml
res/values/arrays.xml
res/values/bool.xml
res/values/strings.xml
res/xml/preferences.xml
src/jmri/enginedriver/Consist.java
src/jmri/enginedriver/ConsistEdit.java
src/jmri/enginedriver/ConsistLightsEdit.java
src/jmri/enginedriver/message_type.java
src/jmri/enginedriver/threaded_application.java
src/jmri/enginedriver/throttle.java

Option to individually control the lights of the Locos in a Consist with a long click on the Loco Select button.

Individually control the lights of the Locos in a Consist

---

res/layout/throttle.xml
res/values/arrays.xml
res/values/strings.xml
src/jmri/enginedriver/Consist.java
src/jmri/enginedriver/ConsistEdit.java
src/jmri/enginedriver/ConsistLightsEdit.java
src/jmri/enginedriver/threaded_application.java
src/jmri/enginedriver/throttle.java

- separated the gamepad indicator code from the volume indicator code. 
- changed Next Throttle so that it goes to next available throttle, not first available throttle 
- added tones on Next Throttle
- Re-labeled option to "Stop All Throttles"  
Todo: 
- still looking at why you need to restart ED after setting the multiple throttle option on, before the Volume indicator fully behaves as expected.

Support for Multiple GamePads - Improvements

---

res/values/arrays.xml
res/values/strings.xml
res/xml/preferences.xml
src/jmri/enginedriver/throttle.java

- Added user selectable actions to the four main buttons and the Start Button
To Do:
1. Add the throttle functions as options
2. Make the DPad user selectable

Gamepad - user selectable actions

---

res/values/arrays.xml
res/values/strings.xml
res/xml/preferences.xml
src/jmri/enginedriver/preferences.java

( It is an option in the Shared Preferences Screen)

New - Export/Import/Reset Shared Preferences

---

src/jmri/enginedriver/preferences.java

Preference did not reset under all conditions

fix - Export/Import/Reset Shared Preferences

---

res/values/strings.xml
res/xml/preferences.xml
src/jmri/enginedriver/throttle.java

1. text/label changes
2. only accept 2 digits (0-99)  i.e. percent
3. automatically disables auto-brightness / adaptive brightness

Change - Mods to the the Dim screen function 

---

res/layout/throttle.xml
res/values/strings.xml

change - added text resources to remove ~100 warning messages

change - slight re-positioning of the functions buttons

---

res/xml/preferences.xml

preference was set to only a length of 2

fix - Maximum Throttle Percentage did not allow 100%

---

AndroidManifest.xml
assets/about_page.html
changelog-and-todo-list.txt
src/jmri/enginedriver/throttle.java

also bump version to test6 as published on web site

 use gamepad nack sound when direction change not allowed

---

res/values/arrays.xml
res/values/strings.xml
src/jmri/enginedriver/connection_activity.java
src/jmri/enginedriver/preferences.java
src/jmri/enginedriver/threaded_application.java

saves/restores to a file name based on cleaned-up version the current host name

change - option to save and restore preferences specific to the current host

---

res/values/arrays.xml
res/values/bool.xml
res/values/strings.xml
res/xml/preferences.xml
src/jmri/enginedriver/ImportExportPreferences.java
src/jmri/enginedriver/connection_activity.java
src/jmri/enginedriver/preferences.java
src/jmri/enginedriver/select_loco.java
src/jmri/enginedriver/threaded_application.java

Substantial re-write of the code and a new, and hopefully more friendly, way to control it from the preferences

change - re-added option to save/restore preferences specific to the current host

---

res/values/arrays.xml
res/xml/preferences.xml
src/jmri/enginedriver/preferences.java
src/jmri/enginedriver/throttle.java

CHANGE - Dropped support for the VR BOX gamepad
CHANGE - preference is disabled if the button is not available on the device
CHANGE - using more descriptive text in the Gamepad Selection preference

CHANGES - Preference labels based of selected gamepad type

---

assets/about_page.html
src/jmri/enginedriver/throttle.java

change the scale speed step calculation to reduce the rounding error

FIX - change the scale speed step calculation to reduce the rounding error

---

assets/about_page.html
res/values/arrays.xml
res/values/strings.xml
res/xml/preferences.xml
src/jmri/enginedriver/throttle.java

Optional alternate labels for the throttle direction buttons

NEW - Optional alternate labels for the throttle direction buttons

---

src/jmri/enginedriver/direction_button.java
src/jmri/enginedriver/throttle.java

NEW - long press on either direction button swaps the text but not the direction.
I did not get as far with this as I intended tonight. The button colours are not working properly yet.
This still uses a list of labels but I will change that to editable text tomorrow night.
The start of the code for checking the gamepad mode is there, but is not being called anywhere.

CHANGED - Optional alternate labels for the throttle direction buttons

---

res/drawable/button_fn_layers_selected_outline.xml
res/drawable/button_layers_selected_outline.xml
res/drawable/button_layers_selected_round.xml
res/drawable/button_stop_layers_selected_outline.xml
res/drawable/button_stop_layers_selected_round.xml
res/drawable/fn_button_states_round_outline.xml
res/drawable/sticky_button_states_round.xml
res/drawable/sticky_button_states_round_outline.xml
res/drawable/stop_button_states_round.xml
res/drawable/stop_button_states_round_outline.xml
res/values/colors.xml
res/values/dimen.xml

Changes to the two new themes to improve visibiltiy of the selected buttons for people with colour issues.

CHANGE - Improve Themes for colour blindness

---

src/jmri/enginedriver/threaded_application.java
src/jmri/enginedriver/throttle.java

Use a different technique to dim the screen on old versions of Android

FIX - Swipe up Screen dimming for older Android

---

assets/about_page.html
res/drawable/button_layers_activated_hovered_outline.xml
res/drawable/button_layers_activated_hovered_round.xml
res/drawable/button_layers_activated_outline.xml
res/drawable/button_layers_activated_round.xml
res/drawable/button_layers_hovered_outline.xml
res/drawable/button_layers_hovered_round.xml
res/values/arrays.xml
res/values/bool.xml
res/values/colors.xml
res/values/dimen.xml
res/values/strings.xml
res/xml/preferences.xml
src/jmri/enginedriver/throttle.java

UPDATE - Option to highlight the Loco selected.
- Removed one option from the highlight preference
- Changed label to 'Additional...' to separate from the original highlighting.
- Changes to the colours of the highlights for the two additional themes.
NEW - option to disable the hardware volume keys
- Disabling the volume keys automatically disables the indicator.

UPDATE - Option to highlight the Loco selected.

---

res/values/strings.xml

Improved gamepad test screen help text and changed a control
label.

Gamepad test string updates

---

res/layout/gamepad_test.xml
res/layout/throttle.xml
res/values/arrays.xml
res/values/strings.xml
src/jmri/enginedriver/gamepad_test.java
src/jmri/enginedriver/throttle.java

UPDATE - modified direction indication when Labels are customised.
UPDATE - shorter list of gamepad options
Common list for both the preferences and the test page
Shorter/simpler names for the option.

UPDATE - Direction Indicators and the gamepad list

---

res/layout/gamepad_test.xml
res/values/strings.xml
src/jmri/enginedriver/gamepad_test.java
src/jmri/enginedriver/throttle.java

NEW - Reset option.  makes ED think no gamepads have been used
NEW - Show a rolling list of key codes

UPDATE - gamepad test page

---

src/jmri/enginedriver/gamepad_test.java

FIX - trap unused keycodes during the test

 FIX - gamepad test page 

---

res/values-v11/themes.xml
res/values/styles.xml
src/jmri/enginedriver/threaded_application.java
src/jmri/enginedriver/throttle.java

FIX - screen flicker in new themes

FIX - Screen flicker in new themes

---

assets/about_page.html
res/values/bool.xml
res/values/strings.xml
res/xml/preferences.xml
src/jmri/enginedriver/connection_activity.java
src/jmri/enginedriver/throttle.java

CHANE - moved most of the common preferences to a function that is called on Create and Resume
NEW - Option to hide the example server.
NEW - option for the volume keys (selected throttle) to follow the last thhrottle touched.

NEW - Connection and Volume Options

---

AndroidManifest.xml
assets/about_page.html
bin/AndroidManifest.xml
res/values/arrays.xml
res/values/strings.xml
res/xml/preferences.xml
src/jmri/enginedriver/preferences.java
src/jmri/enginedriver/shakeDetector.java
src/jmri/enginedriver/throttle.java

NEW - multiple options for when you shake the device
CHANGE - moved a lot of toast message static text in the throttle page to the string resources

NEW - Use the Accelerometer

---

assets/about_page.html
res/values/strings.xml
res/xml/preferences.xml
src/jmri/enginedriver/preferences.java
src/jmri/enginedriver/throttle.java

separate preferences for Volume key and Gamepad speed increments

NEW - Volume key and Gamepad speed increments

---

res/values-en-rAU/strings.xml
res/values-en-rGB/strings.xml
res/values/strings.xml
src/jmri/enginedriver/ImportExportPreferences.java
src/jmri/enginedriver/connection_activity.java
src/jmri/enginedriver/preferences.java
src/jmri/enginedriver/routes.java
src/jmri/enginedriver/throttle.java
src/jmri/enginedriver/turnouts.java

FIX - Selected loco (for volume key control) now correctly changes when you select a new loco.
CHANGE - continued moving most of the toast messages to the resources

FIX - Selected Loco

---

res/values/strings.xml
src/jmri/enginedriver/ImportExportPreferences.java
src/jmri/enginedriver/connection_activity.java
src/jmri/enginedriver/throttle.java

CHANGE - continued moving toast messages to the resources

---

res/values/arrays.xml
res/values/bool.xml
res/values/strings.xml
res/xml/preferences.xml
src/jmri/enginedriver/gamepad_test.java
src/jmri/enginedriver/throttle.java

CHANGE - TTS option for throttle selection
CHANGE - skip gamepad test by pressing "Decrease Speed" three times
NEW - TTS option for gamepad test, and test complete

CHANGE - Gamepad test + TTS options

---

res/values-v11/styles.xml
res/values-v11/themes.xml
res/values/attrs.xml
res/values/bool.xml
res/values/strings.xml
res/values/styles.xml
res/values/themes.xml

FIX - adjusted the colour of the Volume, gamepad and speed step indicators to white text.

FIX - colour of the Volume, gamepad and speed step indicators

---

assets/about_page.html
res/layout/function_settings.xml
res/values-en-rNZ/strings.xml
res/values-it/arrays.xml
res/values-it/strings.xml
res/values-pt/arrays.xml
res/values-pt/strings.xml
res/values/arrays.xml
res/values/strings.xml
res/xml/preferences.xml
src/jmri/enginedriver/gamepad_test.java
src/jmri/enginedriver/preferences.java
src/jmri/enginedriver/threaded_application.java
src/jmri/enginedriver/throttle.java

CHANGES - Further cleanup of the Strings and Arrays in preparation for the additional languages.
NEW - Italian and Portuguese strings and arrays added

CHANGES - Localisations work

---

res/color/btn_text_states_stop_btn_ultra.xml
res/color/btn_text_states_ultra.xml
res/color/fn_btn_text_states_ultra.xml
res/drawable/button_fn_layers_selected_ultra.xml
res/drawable/button_layers_activated_hovered_ultra.xml
res/drawable/button_layers_activated_ultra.xml
res/drawable/button_layers_hovered_ultra.xml
res/drawable/button_layers_selected_ultra.xml
res/drawable/button_stop_layers_selected_ultra.xml
res/drawable/fn_button_states_ultra.xml
res/drawable/sticky_button_states_ultra.xml
res/drawable/stop_button_states_ultra.xml
res/values-it/arrays.xml
res/values-it/strings.xml
res/values-pt/arrays.xml
res/values-pt/strings.xml
res/values-v11/styles.xml
res/values-v11/themes.xml
res/values/arrays.xml
res/values/bool.xml
res/values/colors.xml
res/values/dimen.xml
res/values/strings.xml
res/xml/preferences.xml
src/jmri/enginedriver/threaded_application.java
src/jmri/enginedriver/throttle.java

CHANGES - combine some of the preferences

CHANGES - TTS Preference

---

assets/about_page.html
res/layout/function_settings.xml
res/values-it/strings.xml
res/values-pt/strings.xml
res/values/strings.xml
res/xml/preferences.xml
src/jmri/enginedriver/ConsistLightsEdit.java
src/jmri/enginedriver/function_settings.java
src/jmri/enginedriver/preferences.java
src/jmri/enginedriver/threaded_application.java
src/jmri/enginedriver/throttle.java

NEW - option to reset the Function Labels to the defaults
NEW - option to reduce the number of Default function Labels shown

NEW - Function Default Options

---

res/drawable/button_fn_layers_selected_ultra.xml
res/drawable/button_layers_activated_hovered_ultra.xml
res/drawable/button_layers_activated_ultra.xml
res/drawable/button_layers_hovered_ultra.xml
res/drawable/button_layers_selected_ultra.xml
res/drawable/button_stop_layers_selected_ultra.xml
res/drawable/fn_button_states_ultra.xml
res/drawable/sticky_button_states_ultra.xml
res/drawable/stop_button_states_ultra.xml
res/layout/throttle.xml
res/values-v11/styles.xml
res/values-v11/themes.xml
res/values/attrs.xml
res/values/colors.xml
res/values/dimen.xml
res/values/styles.xml
res/values/themes.xml

Significant changes to the Dark Theme.
Some minor changes to the existing themes.

 CHANGE - Dark Theme changes

---

res/drawable/button_fn_layers_enabled_ultra.xml
res/drawable/button_fn_layers_selected_ultra.xml
res/drawable/button_layers_activated_hovered_ultra.xml
res/drawable/button_layers_activated_ultra.xml
res/drawable/button_layers_enabled_ultra.xml
res/drawable/button_layers_selected_ultra.xml
res/drawable/button_stop_layers_enabled_ultra.xml
res/drawable/button_stop_layers_selected_ultra.xml
res/drawable/fn_button_states_ultra.xml
res/drawable/sticky_button_states_ultra.xml
res/drawable/stop_button_states_ultra.xml
res/values-v11/styles.xml
res/values/dimen.xml

More changes to the Dark Theme.

CHANGE - Dark Theme changes

---

AndroidManifest.xml
assets/about_page.html
changelog-and-todo-list.txt
src/jmri/enginedriver/select_loco.java
src/jmri/enginedriver/threaded_application.java
src/jmri/enginedriver/throttle.java

* only send release for throttles actually in use, shorten delays on shutdown
* prevent crash on bad consist address, crash reported to Play Store

update to -test7

---

res/values/strings.xml
src/jmri/enginedriver/throttle.java

Changed to work on the down press.

CHANGE - long press delay for the direction buttons

---

src/jmri/enginedriver/throttle.java

Consists on Throttles 2&3 would behave incorrectly when first selected.

FIX - Consists on Throttles 2&3

---

src/jmri/enginedriver/threaded_application.java

May help with the crash on steal.

FIX (hopefully) - Crash on Steal

---

src/jmri/enginedriver/throttle.java

wrapped the likely problem code in a try/catch

 FIX - attempt to resolve a reported crash

---

res/layout/select_loco.xml
res/values-it/strings.xml
res/values-pt/strings.xml
res/values/strings.xml
src/jmri/enginedriver/select_loco.java

radio button option to show one of: loco address entry, roster list or recent list

CHANGE - Revised loco select page

---

assets/about_page.html
res/layout/select_loco.xml
res/values-it/strings.xml
res/values-pt/strings.xml
res/values/strings.xml
src/jmri/enginedriver/select_loco.java

small tweaks to the design
plus a few additional translations

 CHANGE - Revised loco select page  

---

assets/about_page.html
res/layout/function_settings.xml
res/layout/select_loco.xml
res/layout/throttle.xml
res/values-it/strings.xml
res/values-pt/strings.xml
res/values-v11/styles.xml
res/values/bool.xml
res/values/strings.xml
res/xml/preferences.xml
src/jmri/enginedriver/Consist.java
src/jmri/enginedriver/Loco.java
src/jmri/enginedriver/connection_activity.java
src/jmri/enginedriver/function_settings.java
src/jmri/enginedriver/preferences.java
src/jmri/enginedriver/select_loco.java
src/jmri/enginedriver/threaded_application.java
src/jmri/enginedriver/throttle.java

CHANGE - remove hide recent options
CHANGE - first restart on theme change
CHANGE - force restart loads preference screen

NEW - separate limit for function buttons for roster entries

---

AndroidManifest.xml
assets/about_page.html
src/jmri/enginedriver/threaded_application.java

prevent crash when EStop requested when not connected

---

res/values/arrays.xml
src/jmri/enginedriver/preferences.java

forgot to remove the menu option

Temporary Removal of German

---

assets/about_page.html
res/values-de/arrays.xml
res/values-de/strings.xml
res/values/arrays.xml

production ready German translations

German Translation

---

res/values-de/strings.xml
src/jmri/enginedriver/throttle.java

hopefully fail gracefully if the tone generator initiation fails

Tone Generator exception check

---

res/values-de-rAT/strings.xml
res/values-de-rCH/strings.xml
res/values-de-rLI/strings.xml
res/values-de/arrays.xml
res/values-de/strings.xml
res/values/strings.xml
src/jmri/enginedriver/threaded_application.java

hardcoded text moved to the strings file.  Corresponding German translations.

Additional Strings.

---

res/values/strings.xml
src/jmri/enginedriver/threaded_application.java

also a bit of auto-reformatting

use getString() parms instead of .replace()

---

assets/about_page-de-rAT-CH-LI.html
assets/about_page-de.html
assets/about_page.html
res/layout/function_settings.xml
res/values-de/strings.xml
res/values-it/strings.xml
res/values-pt/strings.xml
res/values/bool.xml
res/values/strings.xml
res/xml/preferences.xml
src/jmri/enginedriver/throttle.java

NEW - option to force F1 & F2 to be treated as sound 
FIX - layout of the Function Preference screen was weird.

NEW - option to force F1 & F2 to be treated as sound

---

res/values-v11/styles.xml
res/values-v11/themes.xml

still trying to fix the dialog box titles

NEW - Colourful/Colorful Theme

---

res/color/btn_loco_select_text_states_colorful.xml
res/layout/throttle_big_buttons_left.xml
res/values-de/strings.xml
res/values/colors.xml
src/jmri/enginedriver/throttle_big_buttons.java

plus small changes to the  Colourful/Colorful Theme

FIX - for the direction labels in the big button throttle screen

---

EngineDriver/build.gradle
EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/function_settings.java
changelog-and-todo-list.txt

bump MinSDKVersion from 7 to 15

post-Gradle adjustments 4

---

EngineDriver/src/main/AndroidManifest.xml
EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/preferences.java
EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
changelog-and-todo-list.txt

fix a few crashes reported to Play Console

released to Store as 2.22.67 (Beta for now)

---

EngineDriver/src/main/res/values-ca/strings.xml

Commit and push test for catalan and spanish translation.

---

EngineDriver/src/main/assets/about_page-ca.html
EngineDriver/src/main/assets/about_page-es.html
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-es/arrays.xml
EngineDriver/src/main/res/values-es/strings.xml

More corrections of Catalan and Spanish translations.

Corrections of Catalan and Spanish translations.

---

EngineDriver/src/main/java/jmri/enginedriver/Consist.java
EngineDriver/src/main/java/jmri/enginedriver/Loco.java
EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java

include the defaults if not from the roster

store the function labels for each Loco in the consist

---

EngineDriver/src/main/assets/about_page-ca.html
EngineDriver/src/main/assets/about_page-es.html
EngineDriver/src/main/res/values-ca/arrays.xml
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-es/strings.xml

I redid this PR to eliminate the inadvertent deletion of gradlew.bat

Little changes on Catalan and Spanish translation. (from eldelinux)

---

EngineDriver/src/main/java/jmri/enginedriver/throttle.java

A merge at some point moved a line of code to the wrong place

FIX Gamepad test infinite loop bug

---

.gitignore
EngineDriver/build.gradle
EngineDriver/src/main/AndroidManifest.xml
EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/function_settings.java
EngineDriver/src/main/java/jmri/enginedriver/preferences.java
EngineDriver/src/main/java/jmri/enginedriver/shakeDetector.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/util/Flashlight.java
EngineDriver/src/main/java/jmri/enginedriver/util/PermissionsHelper.java
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values/strings.xml

This PR lifts the target API to 26 which is now required for Play Store publication.
As a result of the need to cater for a new permissions model, there's been quite some rework to handle the new runtime permissions model for API 23 and later devices

Changes to lift target API to 26

---

EngineDriver/src/main/java/jmri/enginedriver/gamepad_test.java
EngineDriver/src/main/java/jmri/enginedriver/preferences.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/res/layout/gamepad_test.xml
EngineDriver/src/main/res/values-v11/themes.xml
EngineDriver/src/main/res/values/arrays.xml
EngineDriver/src/main/res/values/colors.xml
EngineDriver/src/main/res/values/integers.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/values/themes.xml
EngineDriver/src/main/res/xml/preferences.xml
build.gradle

NEW - Gamepad functions behave the same as the on screen functions
NEW - Support for Flydigi Wee 2 gamepad
FIX - explicitly set the menu text colour in the themes

NEW - Gamepad functions behave the same as the on screen functions

---

EngineDriver/src/main/java/jmri/enginedriver/ImportExportPreferences.java
EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/intro_activity.java
EngineDriver/src/main/java/jmri/enginedriver/intro_theme.java
EngineDriver/src/main/java/jmri/enginedriver/intro_throttle_name.java
EngineDriver/src/main/java/jmri/enginedriver/intro_throttle_type.java
EngineDriver/src/main/java/jmri/enginedriver/intro_write_settings.java
EngineDriver/src/main/java/jmri/enginedriver/preferences.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/util/PermissionsHelper.java
EngineDriver/src/main/res/layout/intro_theme.xml
EngineDriver/src/main/res/layout/intro_throttle_name.xml
EngineDriver/src/main/res/layout/intro_throttle_type.xml
EngineDriver/src/main/res/layout/intro_write_settings.xml
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-en-rAU/strings.xml
EngineDriver/src/main/res/values-en-rGB/strings.xml
EngineDriver/src/main/res/values-en-rNZ/strings.xml
EngineDriver/src/main/res/values-v11/themes.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/values/styles.xml
EngineDriver/src/main/res/values/themes.xml

FIX - crash when trying to change the brightness
CHANGE - add the extra permissions to the Initial Setups Screens
CHANGE - revision of the radio button options on the initial setup screens
CHANGE - fix of an odd bug when restoring save preferences

Initial Setup Screens plus write setting permissions

---

EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/util/PermissionsHelper.java
EngineDriver/src/main/res/menu-v11/connection_menu.xml
EngineDriver/src/main/res/menu-v11/routes_menu.xml
EngineDriver/src/main/res/menu-v11/turnouts_menu.xml
EngineDriver/src/main/res/menu/about_menu.xml
EngineDriver/src/main/res/menu/connection_menu.xml
EngineDriver/src/main/res/menu/consist_edit_menu.xml
EngineDriver/src/main/res/menu/consist_lights_edit_menu.xml
EngineDriver/src/main/res/menu/function_settings_menu.xml
EngineDriver/src/main/res/menu/gamepad_test.xml
EngineDriver/src/main/res/menu/logviewer_menu.xml
EngineDriver/src/main/res/menu/power_menu.xml
EngineDriver/src/main/res/menu/preferences_menu.xml
EngineDriver/src/main/res/menu/routes_menu.xml
EngineDriver/src/main/res/menu/select_loco_menu.xml
EngineDriver/src/main/res/menu/throttle_menu.xml
EngineDriver/src/main/res/menu/turnouts_menu.xml
EngineDriver/src/main/res/menu/web_menu.xml
changelog-and-todo-list.txt

remove some lint warnings,
rearrange some menus

add permissions bypass for SDK15

---

EngineDriver/src/main/assets/about_page-ca.html
EngineDriver/src/main/assets/about_page-de-rAT-CH-LI.html
EngineDriver/src/main/assets/about_page-de.html
EngineDriver/src/main/assets/about_page-es.html
EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/CountDownTimer.java
EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/message_type.java
EngineDriver/src/main/java/jmri/enginedriver/preferences.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/util/PermissionsHelper.java
EngineDriver/src/main/res/values/bool.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/xml/preferences.xml

NEW - Automatically import preferences from the server on connect
- Only if the file is newer
- asks for confirmation
CHANGE - cleaned out some warning messages
FIX - default to 1 throttle, to try to catch a reported exception

NEW - Automatically import preferences from the server on connect + FIX

---

EngineDriver/src/main/java/jmri/enginedriver/ImportExportPreferences.java
EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/importServerManualEditTextPreference.java
EngineDriver/src/main/java/jmri/enginedriver/message_type.java
EngineDriver/src/main/java/jmri/enginedriver/preferences.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/util/PermissionsHelper.java
EngineDriver/src/main/res/values-ca/arrays.xml
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-de/arrays.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-es/arrays.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-it/arrays.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-pt/arrays.xml
EngineDriver/src/main/res/values-pt/strings.xml
EngineDriver/src/main/res/values/arrays.xml
EngineDriver/src/main/res/values/bool.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/xml/preferences.xml

- only from the current server
- preferences options and triggers changed
- text and toast messages improved
- reset deletes all the auto_*.ed files

CHANGE - Import preferences from the server manually and on connect

---

EngineDriver/src/main/assets/about_page-cs.html
EngineDriver/src/main/res/values-cs/arrays.xml
EngineDriver/src/main/res/values-cs/strings.xml

unification of terminology with the program JMRI

Fix Czech translation

---

EngineDriver/src/main/assets/about_page-cs.html
EngineDriver/src/main/assets/blank_page-cs.html
EngineDriver/src/main/assets/feature_not_available-cs.html
EngineDriver/src/main/assets/web_not_available-cs.html
EngineDriver/src/main/res/values-cs/arrays.xml
EngineDriver/src/main/res/values-cs/strings.xml

replace UTF-8 characters with html entites with latin1

Fix HTML Czech translation

---

EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-cs/strings.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-pt/strings.xml
EngineDriver/src/main/res/values/bool.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/xml/preferences.xml

NEW - Option to have the Recent List shows matching Loco names from the roster
FIX - Lint

NEW - Option to have the Recent List shows matching Loco names from the roster

---

EngineDriver/src/main/AndroidManifest.xml
EngineDriver/src/main/assets/about_page-ca.html
EngineDriver/src/main/assets/about_page-cs.html
EngineDriver/src/main/assets/about_page-de.html
EngineDriver/src/main/assets/about_page-es.html
EngineDriver/src/main/assets/about_page-fr.html
EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/routes.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/turnouts.java
EngineDriver/src/main/java/jmri/enginedriver/web_activity.java
EngineDriver/src/main/res/layout/web_activity.xml
changelog-and-todo-list.txt

NEW - New transparent button added to the web view to allow closing the web view without having to back through the page history.
FIX - missing notification bar added back to the Web View page along with the menu.

FIX - Web View and Auto-Web remember page and position on page

---

EngineDriver/src/main/res/color/primary_text_color_selector_black.xml
EngineDriver/src/main/res/color/secondary_text_color_selector_black.xml
EngineDriver/src/main/res/layout/throttle_big_buttons_left.xml
EngineDriver/src/main/res/layout/throttle_big_buttons_right.xml
EngineDriver/src/main/res/layout/throttle_vertical_left.xml
EngineDriver/src/main/res/layout/throttle_vertical_right.xml
EngineDriver/src/main/res/values/colors.xml
EngineDriver/src/main/res/values/themes.xml
build.gradle
changelog-and-todo-list.txt

FIX - Alignment problems for the Function Buttons on the Big Buttons and Vertical throttle layouts
FIX - Improve the colour of the disabled preferences text on the black themes

FIX - Alignment problems for the Function Buttons

---

EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-cs/strings.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-pt/strings.xml
EngineDriver/src/main/res/values/strings.xml

Google Translations for a number of missing strings in different languages

FIX - Missing Translations

---

EngineDriver/src/main/java/jmri/enginedriver/preferences.java
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-cs/strings.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-pt/strings.xml
EngineDriver/src/main/res/values/strings.xml

FIX - some replaceable parameters in some translations

CHANGE - Import export preference dialog

---

EngineDriver/src/main/java/jmri/enginedriver/ImportExportPreferences.java
EngineDriver/src/main/java/jmri/enginedriver/VerticalSeekBar.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java

FIX - Importing preferences was overwriting the device name
CHANGE - improvements to the tick marks on the vertical sliders

FIX - Importing preferences was overwriting the device name

---

EngineDriver/src/main/java/jmri/enginedriver/select_loco.java

Prevents the NPE in getLocoIconUrlFromRoster captured in the Problem
Report from crownqltesq

Fix for NPE in Problem Report 1

---

EngineDriver/src/main/java/jmri/enginedriver/throttle.java

Fixes for the remaining crashes in Steve's collection.

Fixes for reported crashes

---

EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_big_buttons.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_full.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_simple.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_vertical.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_vertical_left_or_right.java

CHANGE - split the use of maxThrottles and maxThrottlesCurrentScreen
CHANGE - Check for Null Exception in onDestroy

CHANGE - split the use of maxThrottles and maxThrottlesCurrentScreen

---

EngineDriver/src/main/assets/about_page-ca.html
EngineDriver/src/main/assets/about_page-es.html
EngineDriver/src/main/res/values-ca/arrays.xml
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-es/arrays.xml
EngineDriver/src/main/res/values-es/strings.xml
build.gradle

Small grammatical corrections and the translation of new implementations of the translations into Catalan and Spanish.

Translation to Catalan and Spanish

---

EngineDriver/build.gradle
EngineDriver/src/main/java/jmri/enginedriver/select_loco.java

also update compileSDKversion to work with latest gradle build tools

prevent crash when Select pressed before roster is ready.

---

EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-es/strings.xml

Translated consist strings in main menu.

Translated to Catalan and Spanish recent strings added.

---

EngineDriver/src/main/AndroidManifest.xml
EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
changelog-and-todo-list.txt

bump version to 2.25.90 since 89 released to production

 avoid crash when removing roster entry from recents

---

EngineDriver/src/main/java/jmri/enginedriver/Consist.java
EngineDriver/src/main/java/jmri/enginedriver/ConsistEdit.java
EngineDriver/src/main/java/jmri/enginedriver/ConsistLightsEdit.java
EngineDriver/src/main/java/jmri/enginedriver/about_page.java
EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/function_settings.java
EngineDriver/src/main/java/jmri/enginedriver/gamepad_test.java
EngineDriver/src/main/java/jmri/enginedriver/intro_activity.java
EngineDriver/src/main/java/jmri/enginedriver/logviewer/ui/LogViewerActivity.java
EngineDriver/src/main/java/jmri/enginedriver/power_control.java
EngineDriver/src/main/java/jmri/enginedriver/preferences.java
EngineDriver/src/main/java/jmri/enginedriver/reconnect_status.java
EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_big_buttons.java
EngineDriver/src/main/res/values-cs/strings.xml

CHANGE - Hide tick mark preference on default throttle type
FIX - Lint removal

FIX - Permission issue in permission helper

---

EngineDriver/src/main/assets/about_page-ca.html
EngineDriver/src/main/assets/about_page-cs.html
EngineDriver/src/main/assets/about_page-de-rAT-CH-LI.html
EngineDriver/src/main/assets/about_page-de.html
EngineDriver/src/main/assets/about_page-es.html
EngineDriver/src/main/assets/about_page-fr.html
EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/Consist.java
EngineDriver/src/main/java/jmri/enginedriver/gamepad_test.java
EngineDriver/src/main/java/jmri/enginedriver/logviewer/ui/LogViewerActivity.java
EngineDriver/src/main/java/jmri/enginedriver/power_control.java
EngineDriver/src/main/java/jmri/enginedriver/preferences.java
EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_big_buttons.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_full.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_vertical.java
EngineDriver/src/main/res/layout/throttle_vertical.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-pt/strings.xml
EngineDriver/src/main/res/values/arrays.xml
EngineDriver/src/main/res/values/bool.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/xml/preferences.xml

FIX - resolve issue when re-selecting the same loco when using drop before acquire
CHANGE - revised way to restart the app on some preference changes

NEW - option for shunting/switching speed button (on the Vertical Throttle page only)

---

EngineDriver/src/main/java/jmri/enginedriver/reconnect_status.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java

Change the vibrate to a pattern

Play sound and vibrate when device disconnects

---

EngineDriver/src/main/java/jmri/enginedriver/Loco.java
EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
EngineDriver/src/main/res/layout/consists_list_item.xml
EngineDriver/src/main/res/layout/select_loco.xml
EngineDriver/src/main/res/values/strings.xml
build.gradle

Remember on-the-fly consists and select them from list

Recent Consists

---

EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
EngineDriver/src/main/res/layout/consists_list_item.xml
EngineDriver/src/main/res/layout/engine_list_item.xml
EngineDriver/src/main/res/layout/roster_list_item.xml
EngineDriver/src/main/res/layout/throttle_vertical.xml

Bug fixes
Formatting changes
Hide radio buttons if lists are empty

Recent Consists - various

---

EngineDriver/src/main/java/jmri/enginedriver/select_loco.java

+ some lint removal
As you add each loco to the consist, the previous version of the consist (one loco less) is automatically removed.

Recent Consists - when building, forget the earlier versions

---

EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
EngineDriver/src/main/res/values/strings.xml

instead of long press, to be consistent with the other lists

Change the 'remove recent connection' to swipe

---

EngineDriver/src/main/assets/about_page-ca.html
EngineDriver/src/main/assets/about_page-cs.html
EngineDriver/src/main/assets/about_page-de-rAT-CH-LI.html
EngineDriver/src/main/assets/about_page-de.html
EngineDriver/src/main/assets/about_page-es.html
EngineDriver/src/main/assets/about_page-fr.html
EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
changelog-and-todo-list.txt

Locos selected by DCC Address or Recents would not update the Last Operated value

Fix bug - Last Operated value

---

EngineDriver/src/main/java/jmri/enginedriver/preferences.java
EngineDriver/src/main/java/jmri/enginedriver/routes.java
EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/turnouts.java
EngineDriver/src/main/java/jmri/enginedriver/web_activity.java
build.gradle

attempt to stop the notification on rotate

---

EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/ConsistEdit.java
EngineDriver/src/main/java/jmri/enginedriver/ConsistLightsEdit.java
EngineDriver/src/main/java/jmri/enginedriver/ImportExportPreferences.java
EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/res/layout/select_loco.xml
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-cs/strings.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-pt/strings.xml
EngineDriver/src/main/res/values/strings.xml
changelog-and-todo-list.txt

Additional buttons to access the Consist Edit and Consist Lights Edit pages

Recent Consists - remove additional duplicate code

---

EngineDriver/src/main/java/jmri/enginedriver/ImportExportPreferences.java
EngineDriver/src/main/java/jmri/enginedriver/select_loco.java

also don't include direction in the comparisons of consists

Recent Consists - fix timing problem

---

EngineDriver/src/main/java/jmri/enginedriver/ConsistEdit.java
EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_big_buttons.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_full.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_simple.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_vertical.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_vertical_left_or_right.java
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-cs/strings.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-pt/strings.xml
EngineDriver/src/main/res/values/strings.xml

Loco Select - don't allow an already selected loco
also, only show the toast help message once each session.

Loco Select - don't allow an already selected loco

---

EngineDriver/src/main/java/jmri/enginedriver/ConsistEdit.java
EngineDriver/src/main/java/jmri/enginedriver/select_loco.java

recent consists - fix bug where loco facings were not being saved if the edit consist button was used

recent consists - fix bug where loco facings were not being saved

---

EngineDriver/src/main/java/jmri/enginedriver/ImportExportPreferences.java
EngineDriver/src/main/java/jmri/enginedriver/turnouts.java
EngineDriver/src/main/res/layout/turnouts.xml
EngineDriver/src/main/res/values/strings.xml

1. Combined the Address and Recents
2. Only show recents from the current server
3. Only refresh the recents if the entered address is different to the last used

CHANGES - Recent Turnouts/Points functionality

---

EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-cs/strings.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-en-rAU/strings.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-pt/strings.xml
EngineDriver/src/main/res/values/strings.xml

Adjusted the translations to match the last changes

CHANGES - Recent Turnouts/Points functionality - Translations

---

EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/turnouts.java
EngineDriver/src/main/res/layout/turnouts_item.xml
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-cs/strings.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-en-rAU/strings.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-pt/strings.xml
EngineDriver/src/main/res/values/strings.xml
StudioProjects-EngineDriver.iml
build.gradle
gradle/wrapper/gradle-wrapper.properties

FIX - MagicSeeR1 gamepad button A bug fix
Turnouts/Points
Only show the Close/Throw buttons if the state is Unknown.
Show the Toggle button if the state is known.

CHANGES - Turnouts/Points functionality changes

---

EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/turnouts.java

correct problem with refresh of entered addresses

FIX - Recent Turnouts/Points

---

EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_big_buttons.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_full.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_simple.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_vertical.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_vertical_left_or_right.java

FIX - Swipe now works everywhere except active sliders
Fix - Less likely to activate function button when scrolling or swiping

FIX - Swipe now works everywhere except active sliders

---

EngineDriver/src/main/AndroidManifest.xml
EngineDriver/src/main/java/jmri/enginedriver/VerticalSeekBar.java
EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_switching_left_or_right.java
EngineDriver/src/main/java/jmri/enginedriver/web_activity.java
EngineDriver/src/main/res/layout/throttle_switching_left.xml
EngineDriver/src/main/res/layout/throttle_switching_right.xml
EngineDriver/src/main/res/values-ca/arrays.xml
EngineDriver/src/main/res/values-cs/arrays.xml
EngineDriver/src/main/res/values-de/arrays.xml
EngineDriver/src/main/res/values-en-rAU/arrays.xml
EngineDriver/src/main/res/values-en-rGB/arrays.xml
EngineDriver/src/main/res/values-en-rNZ/arrays.xml
EngineDriver/src/main/res/values-es/arrays.xml
EngineDriver/src/main/res/values-fr/arrays.xml
EngineDriver/src/main/res/values-it/arrays.xml
EngineDriver/src/main/res/values-pt/arrays.xml
EngineDriver/src/main/res/values/arrays.xml

NEW - Switching/Shunting Throttle Screen Types

---

EngineDriver/src/main/java/jmri/enginedriver/throttle_switching_left_or_right.java

fix an issue using the speed buttons at zero requiring an extra click

FIX - Switching/Shunting screen layout

---

EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/turnouts.java
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-cs/strings.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-en-rAU/strings.xml
EngineDriver/src/main/res/values-en-rGB/strings.xml
EngineDriver/src/main/res/values-en-rNZ/strings.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-pt/strings.xml
EngineDriver/src/main/res/values/strings.xml
build.gradle
changelog-and-todo-list.txt

CHANGE - add confirm dialogs for clearing recent lists

---

EngineDriver/src/main/java/jmri/enginedriver/ImportExportPreferences.java
EngineDriver/src/main/java/jmri/enginedriver/VerticalSeekBar.java

FIX - more aggressive clean-out of preferences

---

EngineDriver/src/main/java/jmri/enginedriver/VerticalSeekBar.java
EngineDriver/src/main/java/jmri/enginedriver/preferences.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_switching_left_or_right.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_vertical.java
EngineDriver/src/main/res/values/arrays.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/xml/preferences.xml
changelog-and-todo-list.txt

CHANGE - confirm dialog on manual preferences import
CHANGE - confirm dialog on preferences reset
FIX - Switching/Shunting Throttle obeys Max Throttle preference
FIX - Switching/Shunting Throttle forces a zero speed when changing directions with the speed buttons
FIX - Obey speed change limit on Switching/Shunting Throttle sliders
FIX - Obey speed change limit on Vertical Throttle sliders

CHANGES - Preferences and Switching/Shunting Throttle

---

EngineDriver/src/main/java/jmri/enginedriver/throttle_switching_left_or_right.java
EngineDriver/src/main/res/xml/preferences.xml

FIX - don't allow text in the Limit Speed preference
FIX - Max Throttle % is obeyed immediately on start

FIXES - switching/Shunting throttle screen

---

EngineDriver/src/main/java/jmri/enginedriver/ConsistEdit.java
EngineDriver/src/main/java/jmri/enginedriver/ConsistLightsEdit.java
EngineDriver/src/main/java/jmri/enginedriver/about_page.java
EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/function_settings.java
EngineDriver/src/main/java/jmri/enginedriver/logviewer/ui/LogViewerActivity.java
EngineDriver/src/main/java/jmri/enginedriver/power_control.java
EngineDriver/src/main/java/jmri/enginedriver/preferences.java
EngineDriver/src/main/java/jmri/enginedriver/reconnect_status.java
EngineDriver/src/main/java/jmri/enginedriver/routes.java
EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/turnouts.java
EngineDriver/src/main/java/jmri/enginedriver/web_activity.java

Any handled cases in onOptionsItemSelected are supposed to return true, not call the super.  Corrected code accordingly.

Correct onOptionsItemsSelected returns for handled cases

---

EngineDriver/src/main/assets/about_page.html

update about page

---

EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/preferences.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java

Cleanup usage of PermissionsHelper in connection_activity, preferences and throttle.  Will follow with cleanup in remaining activities.

Begin PermissionsHelper usage cleanup

---

EngineDriver/src/main/java/jmri/enginedriver/function_settings.java
EngineDriver/src/main/java/jmri/enginedriver/logviewer/ui/LogViewerActivity.java

Cleanup usage of PermissionsHelper in function_settings and LogViewerActivity.

Continue permissions usage cleanup

---

EngineDriver/src/main/java/jmri/enginedriver/about_page.java
EngineDriver/src/main/java/jmri/enginedriver/gamepad_test.java
EngineDriver/src/main/java/jmri/enginedriver/select_loco.java

When the condition is handled, the public bool overrides in these commits should return true.  The super should be returned only when the condition is not handled.

Correct returns for certain public bool overrides

---

EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java

Implementing a great idea Peter had to change things so that when a Preference change causes a restart then CA relaunches CA and Throttle relaunches Throttle.  This means if you change a theme, etc, after you have already connected then now you will stay connected.
Followed Peter's approach and moved common methods to TA so that they would be accessible to both CA and Throttle.  getThrottleIntent() is used when (re)launching Throttle.  prefsForcedRestart() is used in CA and Throttle onCreate() to see if Preferences need to be shown.  Also moved the restart reason definitions to TA.

revise restart on pref change

---

EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java

Reordered outbound heartbeat interval calculations so that the range check occurs after the response allowance is subtracted.  This fixes a problem with very short WiT heartbeat settings.
Added inbound heartbeat assignment and range checking so that the inbound heartbeat will be used.

heartbeat interval range checking

---

EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/preferences.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/res/layout/throttle.xml
EngineDriver/src/main/res/layout/throttle_big_buttons_left.xml
EngineDriver/src/main/res/layout/throttle_big_buttons_right.xml
EngineDriver/src/main/res/layout/throttle_simple.xml
EngineDriver/src/main/res/layout/throttle_switching_left.xml
EngineDriver/src/main/res/layout/throttle_switching_right.xml
EngineDriver/src/main/res/layout/throttle_vertical.xml
EngineDriver/src/main/res/layout/throttle_vertical_left.xml
EngineDriver/src/main/res/layout/throttle_vertical_right.xml
EngineDriver/src/main/res/values/arrays.xml
EngineDriver/src/main/res/values/bool.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/xml/preferences.xml

Added option (preference) to use a user defined background image on the throttle page

NEW - Background image on the throttle page

---

EngineDriver/src/main/java/jmri/enginedriver/throttle_switching_left_or_right.java
EngineDriver/src/main/res/layout/throttle_switching_right.xml

calculation was incorrect in the shunting/switching throttle page type

FIX - Function Button Scroller height

---

EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-cs/strings.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-pt/strings.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/xml/preferences.xml

CHANGE - additional google translations

---

EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java

Cleaned up background mode handling.  Moved all code actions related to running in background mode to the TA ApplicationLifecycleHandler.  The app now runs the disconnect/shutdown sequence when it is about to get killed in background mode, which results in a clean environment for the next launch of the app.
Fixed string for inboundTimeoutInterval

Background mode

---

EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java

Launch correct activity when resuming from background mode.
Expedite shutdown when killed in background mode.

Background mode improvements

---

EngineDriver/src/main/java/jmri/enginedriver/preferences.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/res/values/arrays.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/xml/preferences.xml

- Throttle Switch Button preferences
- Background Image preferences
Also
- disable the additional preferences if the main one is not checked
- hide all the above if Advanced preferences is not checked

CHANGE - Group some Preferences in Preference Screens

---

EngineDriver/src/main/assets/about_page-fr.html
EngineDriver/src/main/res/layout/checkbox_icon_left_highlight.xml
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-cs/strings.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-fr/arrays.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-pt/strings.xml
EngineDriver/src/main/res/values/colors.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/xml/preferences.xml

NE - Additional French translations by Alain Carasso

CHANGE - tweaks to the Preferences page

---

EngineDriver/src/main/res/values-ca/arrays.xml

More translations into Catalan and changed to lower case some letters of the file arrays.xml.

More translations into Catalan

---

EngineDriver/src/main/res/values-ca/arrays.xml
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-es/arrays.xml

Full translation into Catalan and partial (only array.xml file) into Spanish language.

Catalan and Spanish language translations

---

EngineDriver/src/main/assets/about_page-ca.html
EngineDriver/src/main/assets/about_page-es.html
EngineDriver/src/main/res/values-ca/arrays.xml
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-es/arrays.xml
EngineDriver/src/main/res/values-es/strings.xml

Full translation into Spanish and little changes into Catalan language.

Full translation into Spanish and Catalan

---

EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-es/strings.xml

Add "prefSwitchingThrottleSliderDeadZoneSummary" and "prefSwitchingThrottleSliderDeadZoneTitle" to Spanish "string.xml" file and little changes into Catalan translations files.

Some corrections into Spanish and Catalan translations.

---

EngineDriver/src/main/java/jmri/enginedriver/routes.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/turnouts.java
EngineDriver/src/main/res/menu/routes_menu.xml
EngineDriver/src/main/res/menu/turnouts_menu.xml
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-cs/strings.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-pt/strings.xml

Routes and Points/Turnouts menus

CHANGE - revised action bar and overflow menu

---

EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/res/layout/connection.xml
EngineDriver/src/main/res/values/strings.xml
StudioProjects-EngineDriver.iml
build.gradle
gradle/wrapper/gradle-wrapper.properties

With buttons to allow text entry

CHANGE - default to numeric keyboard for Server Address

---

EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/res/values-ca/arrays.xml
EngineDriver/src/main/res/values-cs/arrays.xml
EngineDriver/src/main/res/values-de/arrays.xml
EngineDriver/src/main/res/values-es/arrays.xml
EngineDriver/src/main/res/values-fr/arrays.xml
EngineDriver/src/main/res/values-it/arrays.xml
EngineDriver/src/main/res/values-pt/arrays.xml
EngineDriver/src/main/res/values/arrays.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/xml/preferences.xml

FIX - retain the web view setting when switching layouts
NEW - additional background layout options

NEW - Swipe down options same as swipe up

---

EngineDriver/src/main/assets/about_page-ca.html
EngineDriver/src/main/assets/about_page-cs.html
EngineDriver/src/main/assets/about_page-de.html
EngineDriver/src/main/assets/about_page-es.html
EngineDriver/src/main/assets/about_page-fr.html
EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/ImportExportConnectionList.java
EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/message_type.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/util/GetJsonFromUrl.java
EngineDriver/src/main/res/layout/connection.xml
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-cs/strings.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-fr/arrays.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-pt/strings.xml
EngineDriver/src/main/res/values/dimen.xml
EngineDriver/src/main/res/values/styles.xml

plus CHANGE - location of the Numeric/Text buttons for server address

NEW - get the server name from the webserver if ip address entered

---

EngineDriver/src/main/java/jmri/enginedriver/ImportExportConnectionList.java
EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java

plus CHANGE - location of the Numeric/Text buttons for server address

FIX - Recent connections. Steve's server issue

---

EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java

I think I have resolved the timing problem

FIX - reload of preferences on server connect

---

EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/ImportExportConnectionList.java
EngineDriver/src/main/java/jmri/enginedriver/VerticalSeekBar.java
EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_big_buttons.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_full.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_simple.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_switching_left_or_right.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_vertical.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_vertical_left_or_right.java
EngineDriver/src/main/res/layout/throttle_switching.xml
EngineDriver/src/main/res/layout/throttle_switching_left.xml
EngineDriver/src/main/res/layout/throttle_switching_right.xml
EngineDriver/src/main/res/layout/throttle_vertical.xml
EngineDriver/src/main/res/layout/throttle_vertical_left.xml
EngineDriver/src/main/res/layout/throttle_vertical_right.xml
EngineDriver/src/main/res/values/bool.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/xml/preferences.xml

CHANGE - Limiting speed change rate also applied to decreases in speed
NEW - Optional Pause button for vertical throttles. Slows loco to zero. Press again to return to previous speed.

NEW - Optional Pause buttons on vertical sliders

---

EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/util/PermissionsHelper.java
changelog-and-todo-list.txt

removal of some experimental code

NEW - Pause and limit speed options for GamePads

---

EngineDriver/src/main/java/jmri/enginedriver/preferences.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_switching_left_or_right.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_vertical.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_vertical_left_or_right.java

No longer uses touches on the slider, so works when the slider is hidden.

Change - rewrite of the Pause function

---

EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java

Add comments to clarify the need for delays when ED is handling DISCONNECT prior to sending the WiT Quit message and doing shutdown()

Improve comments around Quit/shutdown

---

EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/message_type.java
EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
changelog-and-todo-list.txt

reduced several heartbeat minimums to 1 second
removed send of 'N' heartbeat if no speed/dir response from server
disconnect if VN not received in 3 seconds

reduce heartbeat mins to 1s, disconnect if VN not received in 3s

---

EngineDriver/src/main/AndroidManifest.xml
EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-cs/strings.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-pt/strings.xml
EngineDriver/src/main/res/values/bool.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/xml/preferences.xml

Attempt resolve the issue of some phones not being able to connect when the router does not have an internet connection
**Option in the menus to force the WiFi connection.**

Attempt resolve the issue of some phones not being able to connect when the router does not have an internet connection

---

EngineDriver/src/main/java/jmri/enginedriver/ConsistEdit.java
EngineDriver/src/main/java/jmri/enginedriver/ConsistLightsEdit.java
EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/message_type.java
EngineDriver/src/main/java/jmri/enginedriver/power_control.java
EngineDriver/src/main/java/jmri/enginedriver/preferences.java
EngineDriver/src/main/java/jmri/enginedriver/reconnect_status.java
EngineDriver/src/main/java/jmri/enginedriver/routes.java
EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/turnouts.java
EngineDriver/src/main/java/jmri/enginedriver/web_activity.java
EngineDriver/src/main/res/values/arrays.xml

Simply reloading the activities doesn't work.  A full restart is needed

Force restart of the whole app on change of the WiFi / Mobile Data preference change

---

EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
EngineDriver/src/main/res/layout/select_loco.xml

also - force the soft keyboard to open
also - use the 'phone' soft keyboard instead of the numeric keyboard

NEW -  Set focus to the address field if DCC Address selected

---

EngineDriver/src/main/java/jmri/enginedriver/preferences.java
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-cs/strings.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-pt/strings.xml
EngineDriver/src/main/res/values/strings.xml

Correctly show/hide the preference item when the Layout is changed

Simple Throttle Function Buttons Fixes

---

EngineDriver/src/main/assets/about_page-ca.html
EngineDriver/src/main/assets/about_page-cs.html
EngineDriver/src/main/assets/about_page-de-rAT-CH-LI.html
EngineDriver/src/main/assets/about_page-de.html
EngineDriver/src/main/assets/about_page-es.html
EngineDriver/src/main/assets/about_page-fr.html
EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/preferences.java
EngineDriver/src/main/java/jmri/enginedriver/reconnect_status.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/res/drawable/app_splash.xml
EngineDriver/src/main/res/values/bool.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/xml/preferences.xml
build.gradle

plus start of the work to have a better splash screen

New preference to disable the sound and vibrate on disconnect

---

EngineDriver/src/main/res/xml/preferences.xml

Fix - show numeric keypad for Dead Zone preference

---

EngineDriver/src/main/java/jmri/enginedriver/throttle_simple.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_switching_left_or_right.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_vertical_left_or_right.java
EngineDriver/src/main/res/xml/preferences.xml

Fix - stop button button not showing on the vertical layouts if the slider is hidden

Fix - stop button button not showing on the vertical layouts if the slider is hidden

---

EngineDriver/src/main/java/jmri/enginedriver/VerticalSeekBar.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/res/values/arrays.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/xml/preferences.xml

Only currently works with the vertical sliders and the speed buttons (not the horizontal slider)
{Preferences under "speed slider and buttons" group for
- enable/disable
- number of steps
- vibration duration

NEW - Experimental haptic feedback

---

EngineDriver/src/main/java/jmri/enginedriver/HorizontalSeekBar.java
EngineDriver/src/main/java/jmri/enginedriver/VerticalSeekBar.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_full.java
EngineDriver/src/main/res/layout/throttle.xml

Horizontal throttle now working.
reduced redundant vibrations.

FIX - Experimental haptic feedback

---

EngineDriver/src/main/java/jmri/enginedriver/throttle_switching_left_or_right.java

would act like pause button if last used the slider to change speed.

FIX - Limit Speed on vertical shunting layout bug

---

EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/res/values/strings.xml

only disable the sound, not the whole notification

FIX - Audible (only) alert preference

---

EngineDriver/src/main/AndroidManifest.xml
EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_big_buttons.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_full.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_simple.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_switching_horizontal.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_switching_left_or_right.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_vertical_left_or_right.java
EngineDriver/src/main/res/values-cs/strings.xml
EngineDriver/src/main/res/values-en-rGB/arrays.xml
EngineDriver/src/main/res/values-en-rNZ/arrays.xml
EngineDriver/src/main/res/values/strings.xml
changelog-and-todo-list.txt

also - Rename of the write system preference

FIX - Hiding the Toolbar in Immersive mode

---

EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java

in immersive mode only allow swipe when the toolbar is actually visible

FIX - only allow swipe when the toolbar is actually visible

---

EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_switching_horizontal.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_switching_left_or_right.java
EngineDriver/src/main/res/layout/intro_buttons.xml
EngineDriver/src/main/res/layout/intro_theme.xml
EngineDriver/src/main/res/layout/throttle_switching.xml
EngineDriver/src/main/res/layout/throttle_switching_horizontal.xml
EngineDriver/src/main/res/layout/throttle_switching_left.xml
EngineDriver/src/main/res/layout/throttle_switching_right.xml
EngineDriver/src/main/res/values-ca/arrays.xml
EngineDriver/src/main/res/values-cs/arrays.xml
EngineDriver/src/main/res/values-de/arrays.xml
EngineDriver/src/main/res/values-en-rAU/arrays.xml
EngineDriver/src/main/res/values-en-rGB/arrays.xml
EngineDriver/src/main/res/values-en-rNZ/arrays.xml
EngineDriver/src/main/res/values-es/arrays.xml
EngineDriver/src/main/res/values-it/arrays.xml
EngineDriver/src/main/res/values-pt/arrays.xml
EngineDriver/src/main/res/values/arrays.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/values/styles.xml

Plus a bug fix introduced by the timer changes

Improvements to the Direction Indicator for the Shunting/Switching layout

---

EngineDriver/src/main/assets/about_page-fr.html
EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-cs/strings.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-fr/arrays.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-pt/strings.xml
EngineDriver/src/main/res/values/strings.xml

Additional French translations

Confirmation dialog of Clear Consists

---

EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_switching_horizontal.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_switching_left_or_right.java

- disabled throttles were showing 100%

Fix - Shunting/Switching layout not updating correctly

---

EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/xml/preferences.xml

no longer requires an app restart to take effect

Fix - Dead Zone Preference Change

---

EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
EngineDriver/src/main/res/values/arrays.xml
EngineDriver/src/main/res/xml/preferences.xml

- Adding the categories to the sub-menus broke the fix to hide the advanced preferences in the sub-menus

Category headings sub-menus Advanced Pref fix

---

EngineDriver/src/main/res/values/arrays.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/xml/preferences.xml

Additional Cleanup of the Preferences

Additional Cleanup of the Preferences

---

EngineDriver/src/main/AndroidManifest.xml
EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java

First steps to only loading necessary sounds
- only load all sounds if the option is set
- reload and reset all sounds on preference changes

'in device' loco sounds

---

EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java

Fix - sounds not stopping when reset to "none"

'in device' loco sounds - fix

---

EngineDriver/build.gradle
EngineDriver/src/main/AndroidManifest.xml
EngineDriver/src/main/java/jmri/enginedriver/ImportExportConnectionList.java
EngineDriver/src/main/java/jmri/enginedriver/ImportExportPreferences.java
EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/function_consist_settings.java
EngineDriver/src/main/java/jmri/enginedriver/function_settings.java
EngineDriver/src/main/java/jmri/enginedriver/intro_activity.java
EngineDriver/src/main/java/jmri/enginedriver/intro_alert.java
EngineDriver/src/main/java/jmri/enginedriver/logviewer/ui/LogViewerActivity.java
EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/util/PermissionsHelper.java
EngineDriver/src/main/res/layout/intro_alert.xml
EngineDriver/src/main/res/values/strings.xml

- change to use 'Scoped Storage'
- copy original files to scoped storage

Update target API level to 30

---

EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-cs/strings.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-pt/strings.xml
EngineDriver/src/main/res/values/strings.xml

Update target API level to 30 + sounds

---

EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java

In Device sounds 

---

EngineDriver/src/main/AndroidManifest.xml
EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/device_sounds_settings.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/res/layout/device_sounds_settings.xml
EngineDriver/src/main/res/menu/device_sounds_settings.xml
EngineDriver/src/main/res/menu/throttle_menu.xml
EngineDriver/src/main/res/values/strings.xml

- stop button - play idle sound now if only one throttle active
- stop crash if the engine_driver folder has nothing is in it on first install.

In Device sounds + API update 

---

EngineDriver/src/main/java/jmri/enginedriver/intro_activity.java
EngineDriver/src/main/res/values/strings.xml

- only show the new intro page if a new connections page does not exists

API update - Android 4

---

EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/ImportExportPreferences.java
EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
changelog-and-todo-list.txt

- import/export was still looking at the old location
- loco sounds would crash if using one of the single throttle layouts

API update + In Device Loco Sounds

---

EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
EngineDriver/src/main/java/jmri/enginedriver/device_sounds_settings.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/util/ArrayQueue.java
EngineDriver/src/main/res/layout/device_sounds_settings.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/xml/preferences.xml
originals/in_device_sounds_outline.svg

- loco sound momentum option (defaults to 750 milliseconds)
- split bell and horn/whistle volumes
- bell and horn/whistle play start-loop-end sounds

In Device Loco Sounds

---

EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-cs/strings.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-pt/strings.xml

- google translations for the sound text

In Device Loco Sounds - translations 

---

EngineDriver/src/main/java/jmri/enginedriver/device_sounds_settings.java
EngineDriver/src/main/res/layout/device_sounds_settings.xml
EngineDriver/src/main/res/values/arrays.xml
EngineDriver/src/main/res/values/styles.xml

Change the volumes on the sound setting page to spinners  (Not the preferences)

Change the volumes on the sound setting page to spinners

---

EngineDriver/src/main/assets/about_page-fr.html
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-cs/strings.xml
EngineDriver/src/main/res/values-de-rAT/strings.xml
EngineDriver/src/main/res/values-de-rCH/strings.xml
EngineDriver/src/main/res/values-de-rLI/strings.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-pt/strings.xml
EngineDriver/src/main/res/values/strings.xml

plus additional French translations

fix references to the old engine_driver folder

---

EngineDriver/src/main/java/jmri/enginedriver/routes.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/turnouts.java
EngineDriver/src/main/java/jmri/enginedriver/web_activity.java
EngineDriver/src/main/res/values/strings.xml

Additional message handler checks.
Ending the gesture handler on exit.

Additional message handler checks.

---

EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
EngineDriver/src/main/java/jmri/enginedriver/logviewer/ui/LogViewerActivity.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-cs/strings.xml
EngineDriver/src/main/res/values-de-rAT/strings.xml
EngineDriver/src/main/res/values-de-rCH/strings.xml
EngineDriver/src/main/res/values-de-rLI/strings.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-pt/strings.xml
EngineDriver/src/main/res/values/strings.xml

Referenced the wrong location on the server (was actually using the old device folder name)

Fix - Auto Server preference load not working

---

EngineDriver/src/main/java/jmri/enginedriver/throttle.java
changelog-and-todo-list.txt

- FIX - mute button not showing/hiding on sound profile change  - Horizontal layouts

In Phone Loco Sounds

---

EngineDriver/src/main/java/jmri/enginedriver/device_sounds_settings.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/res/layout/device_sounds_settings.xml
EngineDriver/src/main/res/values/arrays.xml
EngineDriver/src/main/res/values/bool.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/xml/preferences.xml

- preference to play the loco loop/step sounds till the end when changing speed steps.
- a bit of lint removal

IPLS - don't clip loop sounds

---

EngineDriver/src/main/res/drawable/button_fn_layers_selected_colorful.xml
EngineDriver/src/main/res/values-en-rCA/arrays.xml
EngineDriver/src/main/res/values-en-rCA/strings.xml
EngineDriver/src/main/res/values/colors.xml

Plus - Add Canadian English Locality

Improve Function Button colour in Colourful Theme

---

EngineDriver/src/main/AndroidManifest.xml
EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/res/values/arrays.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/xml/preferences.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties

- TTS fix for Android 11
- add option for TTS on speed Zero and speed Max on the gamepad
- tidy up of the IPLS preferences in the Preference activity
- move the haptic preferences to top level

Text to Speech

---

EngineDriver/src/main/assets/about_page-ca.html
EngineDriver/src/main/assets/about_page-cs.html
EngineDriver/src/main/assets/about_page-de-rAT-CH-LI.html
EngineDriver/src/main/assets/about_page-de.html
EngineDriver/src/main/assets/about_page-es.html
EngineDriver/src/main/assets/about_page-fr.html
EngineDriver/src/main/java/jmri/enginedriver/util/InPhoneLocoSoundsLoader.java

- better checking for the existence of each file
- better cleanup if it doesn't exist
- better error messages

FIX - IPLS Custom Sounds - Add fault tolerance

---

EngineDriver/src/main/java/jmri/enginedriver/gamepad_test.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/res/values/strings.xml

- additional function commands
- fix for non-latching function buttons when specifying the throttle number
- improvements for non-latching functions

Option to use a normal keyboard (bluetooth or USB) as a gamepad type

---

EngineDriver/src/main/java/jmri/enginedriver/intro_activity.java
EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/res/layout/roster_list_item.xml

The images are preloaded from the cache and the downloader replaces them as it finds them.

Cache Roster image files and show them on the recents and roster lists

---

EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java

- change to which characters are filtered out of the file names

Cache Roster images files and show them on the recents and roster lists

---

EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
EngineDriver/src/main/java/jmri/enginedriver/gamepad_test.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/res/values-fr/arrays.xml
EngineDriver/src/main/res/values/arrays.xml

This can't have worked since the change from preference.java to SettingActivity.java and no one has noticed
plus the setup for the new DIY 3x4 keypad gamepad type

FIX - Manual Host preferences Import Export

---

EngineDriver/src/main/java/jmri/enginedriver/web_activity.java

hopefully won't reset every time open the web view.

Attempt to preserve the Web Activity status

---

EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/res/layout/roster_entry.xml
EngineDriver/src/main/res/layout/routes.xml
EngineDriver/src/main/res/values/strings.xml
changelog-and-todo-list.txt

Option to use a local image as the roster image

---

EngineDriver/src/main/AndroidManifest.xml
EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
EngineDriver/src/main/java/jmri/enginedriver/routes.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_switching_left_or_right.java
EngineDriver/src/main/java/jmri/enginedriver/turnouts.java
EngineDriver/src/main/java/jmri/enginedriver/util/InPhoneLocoSoundsLoader.java
EngineDriver/src/main/java/jmri/enginedriver/web_activity.java
EngineDriver/src/main/res/layout/toolbar.xml
EngineDriver/src/main/res/layout/web_activity.xml
EngineDriver/src/main/res/values/arrays.xml
EngineDriver/src/main/res/values/bool.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/xml/preferences.xml

Option to show the Server Description on the Action bar. Intended primarily for devs/testers
PLUS remove code added in the attempt to resolve the web page refresh problem (it didn't work)

Option to show the Server Description on the Action bar

---

EngineDriver/src/main/AndroidManifest.xml
EngineDriver/src/main/java/jmri/enginedriver/routes.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/turnouts.java
EngineDriver/src/main/java/jmri/enginedriver/web_activity.java

FIX Preserve Web activity state - AUTO-WEB

---

EngineDriver/src/main/AndroidManifest.xml
EngineDriver/src/main/java/jmri/enginedriver/reconnect_status.java
EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java

Also trim spaces on cached images

FIX - Engine Driver not appearing in recent apps list.

---

EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/res/values/arrays.xml

- gamepad test (in settings) would crash
- IPLS would not would if set to the DPad actions
- unavailable buttons would show as available

FIX - gamepad issues

---

EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_big_buttons.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_full.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_simple.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_switching_horizontal.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_switching_left_or_right.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_vertical_left_or_right.java
EngineDriver/src/main/res/values-ca/arrays.xml
EngineDriver/src/main/res/values-cs/arrays.xml
EngineDriver/src/main/res/values-de/arrays.xml
EngineDriver/src/main/res/values-es/arrays.xml
EngineDriver/src/main/res/values-fr/arrays.xml
EngineDriver/src/main/res/values-it/arrays.xml
EngineDriver/src/main/res/values-pt/arrays.xml
EngineDriver/src/main/res/values/arrays.xml
EngineDriver/src/main/res/values/strings.xml
changelog-and-todo-list.txt

fixes a bug in the TTS speeds for non-switching layouts
fixes a bug in the TTS preferences that incorrectly disables one option

option for TTS to speak the max speed

---

EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-cs/strings.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-pt/strings.xml
EngineDriver/src/main/res/values/strings.xml

plus fixes for the static text - location of the server preference files

Fix - gamepad buttons if default function labels set to 0 (zero).

---

EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-cs/strings.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-pt/strings.xml
EngineDriver/src/main/res/values/bool.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/xml/preferences.xml

New - Option to specify only one gamepad

---

EngineDriver/src/main/java/jmri/enginedriver/reconnect_status.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/res/layout/reconnect_page.xml
EngineDriver/src/main/res/menu/reconnect_status_menu.xml

Show menu on Disconnect Screen.
- View Log
- Exit
Also try to be a bit more aggressive if you do exit from that screen

Show menu on Disconnect Screen.

---

EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/xml/preferences.xml

a) Add a Preference to alter the Heartbeat Response Factor (percentage of the heartbeat period)
b) change to default to 80%

New: Preference to alter the Heartbeat Response Factor 

---

EngineDriver/build.gradle
EngineDriver/src/main/AndroidManifest.xml
EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/VerticalSeekBar.java
EngineDriver/src/main/java/jmri/enginedriver/dcc_ex.java
EngineDriver/src/main/java/jmri/enginedriver/message_type.java
EngineDriver/src/main/java/jmri/enginedriver/util/comm_handler.java
EngineDriver/src/main/java/jmri/enginedriver/util/comm_thread.java
EngineDriver/src/main/res/layout/dcc_ex.xml
EngineDriver/src/main/res/layout/select_loco.xml
EngineDriver/src/main/res/menu/dcc_ex_menu.xml
EngineDriver/src/main/res/values/arrays.xml
EngineDriver/src/main/res/values/strings.xml

addition of Programming on the Main options
+ correct a misalignment problem with the vertical throttles

DCC-EX native command support

---

EngineDriver/src/main/AndroidManifest.xml
EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/intro_activity.java
EngineDriver/src/main/java/jmri/enginedriver/message_type.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/util/comm_handler.java
EngineDriver/src/main/java/jmri/enginedriver/util/comm_thread.java
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/xml/auto_backup_rules.xml
EngineDriver/src/main/res/xml/auto_backup_rules_new.xml

- more fixed for CSs with no defined Points or Routes
- cloud backup and restore for the preferences and files

DCC-EX native command support + cloud backup and restore

---

EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_vertical_left_or_right.java
EngineDriver/src/main/java/jmri/enginedriver/util/SwipeDetector.java
EngineDriver/src/main/res/layout/throttle_vertical_tablet_left.xml
EngineDriver/src/main/res/values-ca/arrays.xml
EngineDriver/src/main/res/values-cs/arrays.xml
EngineDriver/src/main/res/values-de/arrays.xml
EngineDriver/src/main/res/values-en-rAU/arrays.xml
EngineDriver/src/main/res/values-en-rGB/arrays.xml
EngineDriver/src/main/res/values-en-rNZ/arrays.xml
EngineDriver/src/main/res/values-es/arrays.xml
EngineDriver/src/main/res/values-fr/arrays.xml
EngineDriver/src/main/res/values-it/arrays.xml
EngineDriver/src/main/res/values-pt/arrays.xml
EngineDriver/src/main/res/values/arrays.xml

+Fix for when deleting servers from the recent list

New 'Tablet Vertical Let (1-6)' throttle screen layout

---

EngineDriver/src/main/AndroidManifest.xml
EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
EngineDriver/src/main/java/jmri/enginedriver/gamepad_test.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_switching_horizontal.java
EngineDriver/src/main/res/values-fr/arrays.xml
EngineDriver/src/main/res/values/arrays.xml
EngineDriver/src/main/res/values/integers.xml

- Horizontal Switching bug fix
- Additional options for Mocute gamepads (to help for faulty devices)

Horizontal Switching bug fix

---

EngineDriver/src/main/java/jmri/enginedriver/util/comm_thread.java

automatically create the DCC Turnout/Point if not found

DCC-EX fix for undefined Turnouts/Points

---

EngineDriver/src/main/res/values/arrays.xml
EngineDriver/src/main/res/values/strings.xml

- Only show in advanced preferences
- revised summary text

prefAlwaysUseFunctionsFromServer - minor changes

---

EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/ImportExportPreferences.java
EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
EngineDriver/src/main/java/jmri/enginedriver/about_page.java
EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/function_settings.java
EngineDriver/src/main/java/jmri/enginedriver/logviewer/ui/LogViewerActivity.java
EngineDriver/src/main/java/jmri/enginedriver/routes.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/util/comm_thread.java
changelog-and-todo-list.txt

improve throttle name uniqueness, add DCC-EX Protocol indication to About page

---

EngineDriver/src/main/AndroidManifest.xml
EngineDriver/src/main/java/jmri/enginedriver/dcc_ex.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/res/values/strings.xml

Provide a textual description of the bit values when you read CV29 on the DCC-EX page

DCC-EX CV 29 read improvements

---

EngineDriver/build.gradle
EngineDriver/src/main/AndroidManifest.xml
EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/intro_activity.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/util/PermissionsHelper.java
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-cs/strings.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-pt/strings.xml
EngineDriver/src/main/res/values/strings.xml
changelog-and-todo-list.txt

- Permission changes to support API level 33
- Remove check for legacy files

Permission changes to support API level 33

---

EngineDriver/src/main/AndroidManifest.xml
EngineDriver/src/main/java/jmri/enginedriver/intro_activity.java
EngineDriver/src/main/java/jmri/enginedriver/util/PermissionsHelper.java
changelog-and-todo-list.txt

For Android 10+ - option to retain all data on uninstall
uses the manifest flag -  android:hasFragileUserData="true"

For Android 10+ - option to retain all data on uninstall

---

EngineDriver/src/main/AndroidManifest.xml
EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/intro_activity.java
EngineDriver/src/main/java/jmri/enginedriver/util/PermissionsHelper.java
EngineDriver/src/main/res/values/strings.xml

NEARBY_WIFI_DEVICES does allow you to see the SSID name needed for DCC-EX to fudge the server

API 33 - returned to using Fine Location permission

---

EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/ConsistEdit.java
EngineDriver/src/main/java/jmri/enginedriver/ConsistLightsEdit.java
EngineDriver/src/main/res/layout/consist.xml
EngineDriver/src/main/res/layout/consist_lights.xml
EngineDriver/src/main/res/values/strings.xml
changelog-and-todo-list.txt

Added close button to the Consist Light Edit screen 
Added close buttons to the Consist Edit screen 
Also fixed a bug where the instruction text on the Consist Edit screen was always 'off screen'

Added close buttons to the Consist Edit and Consist Light Edit screens 

---

EngineDriver/build.gradle
EngineDriver/src/main/AndroidManifest.xml
EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/dcc_ex.java
EngineDriver/src/main/java/jmri/enginedriver/message_type.java
EngineDriver/src/main/java/jmri/enginedriver/power_control.java
EngineDriver/src/main/java/jmri/enginedriver/routes.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/util/comm_handler.java
EngineDriver/src/main/java/jmri/enginedriver/util/comm_thread.java
EngineDriver/src/main/res/layout/dcc_ex.xml
EngineDriver/src/main/res/layout/power_control.xml
EngineDriver/src/main/res/layout/routes_item.xml
changelog-and-todo-list.txt

Added support for new DCC-EX EXRAIL commands:
ROUTE_INACTIVE(id), ROUTE_ACTIVE(id), ROUTE_HIDDEN(id), ROUTE_CAPTION(id,"label")
Allows 'Route' button labels and visibility to be changed dynamically

Added support for new DCC-EX EXRAIL commands

---

EngineDriver/src/main/java/jmri/enginedriver/ImportExportConnectionList.java
EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/util/comm_thread.java
EngineDriver/src/main/res/layout/connections_list_item.xml

also added, and remember, the ssids (to help with troubleshooting connections)

Restructure of the item list on the connection page

---

EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
EngineDriver/src/main/java/jmri/enginedriver/comms/comm_thread.java
EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/res/values-ca/strings.xml

to hopefully get around a new security requirement from the Play Store

Remove use of Settings.Secure.ANDROID_ID

---

EngineDriver/src/main/java/jmri/enginedriver/comms/comm_thread.java
EngineDriver/src/main/res/layout/throttle_vertical.xml

bug fix for Vertical throttle
+ catch for invalid version numbers in DCC-EX devel builds

bug fix for Vertical throttle

---

EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/dcc_ex.java
EngineDriver/src/main/java/jmri/enginedriver/intro/intro_activity.java
EngineDriver/src/main/java/jmri/enginedriver/intro/intro_dccex.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/res/layout/intro_dccex.xml
EngineDriver/src/main/res/values/strings.xml
changelog-and-todo-list.txt

+ add intro/setup wizard page for DCC-EX
+ fix for not being able to click on the new buttons on the DCC-EX page (needed to click on the text)

add intro/setup wizard page for DCC-EX

---

EngineDriver/src/main/java/jmri/enginedriver/dcc_ex.java
EngineDriver/src/main/java/jmri/enginedriver/routes.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/turnouts.java
EngineDriver/src/main/java/jmri/enginedriver/withrottle_cv_programmer.java
EngineDriver/src/main/res/layout/withrottle_cv_programmer.xml
EngineDriver/src/main/res/values/strings.xml

+ restrict some CVs from being changed (1, 17, 18 and bit 5 of CV29)

better support for long/short addresses in PoM

---

EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/withrottle_cv_programmer.java
EngineDriver/src/main/res/layout/withrottle_cv_programmer.xml
EngineDriver/src/main/res/values/strings.xml

- impose limits on each of the three values

- remember PoM values

---

EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/comms/comm_thread.java
changelog-and-todo-list.txt

- issue only seen in the JMRI DCC++ simulator

bug fix for <p 0|1>  (space after p)

---

EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/import_export/ImportExportConnectionList.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/res/layout/connections_list_item.xml

I am capturing the service type in the recent connections history.
at the moment I am not actually doing anything with that but I plan to in the future.
This PR fixes a bug where the service type was appearing (it should not) and was repeated in the historic connections in the UI.

Fixes for capturing the Service type

---

EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
EngineDriver/src/main/java/jmri/enginedriver/comms/comm_thread.java
EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/function_consist_settings.java
EngineDriver/src/main/java/jmri/enginedriver/import_export/ImportExportPreferences.java
EngineDriver/src/main/java/jmri/enginedriver/routes.java
EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_switching_horizontal.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_switching_left_or_right.java
EngineDriver/src/main/java/jmri/enginedriver/turnouts.java
EngineDriver/src/main/java/jmri/enginedriver/type/Loco.java
EngineDriver/src/main/java/jmri/enginedriver/type/auto_import_export_option_type.java
EngineDriver/src/main/java/jmri/enginedriver/type/consist_function_rule_style_type.java
EngineDriver/src/main/java/jmri/enginedriver/type/import_export_option_type.java
EngineDriver/src/main/java/jmri/enginedriver/type/kids_timer_action_type.java
EngineDriver/src/main/java/jmri/enginedriver/type/restart_reason_type.java
EngineDriver/src/main/java/jmri/enginedriver/type/screen_swipe_index_type.java
EngineDriver/src/main/java/jmri/enginedriver/type/sort_type.java
EngineDriver/src/main/java/jmri/enginedriver/web_activity.java
EngineDriver/src/main/res/layout/select_loco.xml

plus a bit of tidying of the code

Added loco select lists sort buttons

---

EngineDriver/src/main/assets/about_page-fr.html
EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/comms/comm_thread.java
EngineDriver/src/main/java/jmri/enginedriver/routes.java
EngineDriver/src/main/java/jmri/enginedriver/turnouts.java
EngineDriver/src/main/java/jmri/enginedriver/type/sort_type.java
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values/strings.xml
changelog-and-todo-list.txt

- bug fix for the Automation button labels in DCC-EX
- bug fix for ROUTE_DISABLE() DCC-EX capability
- Additional French Translations by Alain Carasso

Bug fixes and Translations

---

EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/ConsistEdit.java
EngineDriver/src/main/java/jmri/enginedriver/ConsistLightsEdit.java
EngineDriver/src/main/java/jmri/enginedriver/import_export/ImportExportConnectionList.java
EngineDriver/src/main/java/jmri/enginedriver/import_export/ImportExportPreferences.java
EngineDriver/src/main/java/jmri/enginedriver/logviewer/ui/LogViewerActivity.java
EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/type/Consist.java
EngineDriver/src/main/java/jmri/enginedriver/type/Loco.java
EngineDriver/src/main/java/jmri/enginedriver/type/light_follow_type.java
EngineDriver/src/main/java/jmri/enginedriver/util/TransparentListView.java
EngineDriver/src/main/java/jmri/enginedriver/withrottle_cv_programmer.java
EngineDriver/src/main/res/layout/throttle_switching.xml
EngineDriver/src/main/res/values/styles.xml
changelog-and-todo-list.txt

- automatically reduce the font size of buttons if the first word is long or the total text length is long

---

EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_semi_realistic.java
EngineDriver/src/main/java/jmri/enginedriver/type/tick_type.java
EngineDriver/src/main/java/jmri/enginedriver/util/VerticalSeekBar.java
EngineDriver/src/main/res/layout/connection.xml
EngineDriver/src/main/res/layout/throttle_semi_realistic_left.xml
EngineDriver/src/main/res/values/arrays.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/xml/preferences.xml
changelog-and-todo-list.txt

* Semi-Realistic Throttle layout - Optional number of steps for the Load an Brake sliders
* Connect Screen - Disable the connect button if no IP/host name AND port

* Semi-Realistic Throttle layout - Brake no longer completely overrides the throttle

---

EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_semi_realistic.java
EngineDriver/src/main/java/jmri/enginedriver/type/pref_gamepad_button_option_type.java
EngineDriver/src/main/java/jmri/enginedriver/type/tts_msg_type.java
EngineDriver/src/main/java/jmri/enginedriver/util/Tts.java
EngineDriver/src/main/res/values-ca/arrays.xml
EngineDriver/src/main/res/values-cs/arrays.xml
EngineDriver/src/main/res/values-de/arrays.xml
EngineDriver/src/main/res/values-es/arrays.xml
EngineDriver/src/main/res/values-fr/arrays.xml
EngineDriver/src/main/res/values-it/arrays.xml
EngineDriver/src/main/res/values-pt/arrays.xml
EngineDriver/src/main/res/values/arrays.xml
EngineDriver/src/main/res/values/integers.xml
EngineDriver/src/main/res/values/strings.xml

* Semi-Realistic Throttle - Added support for Volume keys
* Semi-Realistic Throttle - Added Gamepad Support
* Semi-Realistic Throttle - Added Keyboard Support
* Semi-Realistic Throttle - modified the way the Load slider impacts momentum. Setting the steps to greater then 2 will now have a more dramatic effect

Semi-Realistic Throttle - Enhancements

---

EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_semi_realistic.java
EngineDriver/src/main/java/jmri/enginedriver/type/tick_type.java
EngineDriver/src/main/java/jmri/enginedriver/util/VerticalSeekBar.java
EngineDriver/src/main/res/layout/throttle_semi_realistic_left.xml
EngineDriver/src/main/res/values/arrays.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/xml/preferences.xml

* Semi-Realistic Throttle - separate Acceleration and Deceleration default delay preferences. Default deceleration is considerably slower. 
* Semi-Realistic Throttle - The Load slider now has an exponential impact on momentum.

Semi-Realistic Throttle improvements

---

EngineDriver/src/main/AndroidManifest.xml
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_semi_realistic.java
EngineDriver/src/main/res/layout/throttle_semi_realistic_left.xml
EngineDriver/src/main/res/values/attrs.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/values/themes.xml
EngineDriver/src/main/res/xml/preferences.xml

- Implementation of a simple emulation of the Air Brake Reservoir.
- There is a simple indicator beside the brake slider of the state of the Reservoir.
- Using the brakes partly or fully drains the Reservoir.
- You are now restricted as to how quickly you can back off the brakes, or reapply the brakes depending on the state of the Reservoir.

* Semi-Realistic Throttle - implementation of a simple emulation of the Air Brake Reservoir.

---

EngineDriver/src/main/AndroidManifest.xml
EngineDriver/src/main/java/jmri/enginedriver/function_consist_settings.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/util/HorizontalSeekBar.java
EngineDriver/src/main/res/menu/throttle_menu.xml
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-cs/strings.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-pt/strings.xml
EngineDriver/src/main/res/values/strings.xml

* Allow the Default Function Settings screen to be available always (Latching/Not Latching)
* Increased logging for gamepad actions
European decoders used F2 to turn Sounds on, but it is not latching by default.  the 'Default Function Settings' screen allows you to change that behaviour.

Allow the Default Function Settings screen to be available always (Latching/Not Latching)

---

EngineDriver/src/main/java/jmri/enginedriver/function_consist_settings.java
EngineDriver/src/main/java/jmri/enginedriver/function_settings.java
EngineDriver/src/main/res/layout/function_consist_settings.xml
EngineDriver/src/main/res/values/styles.xml
changelog-and-todo-list.txt

* Bug fix for the Close button on the Function Defaults screen
* Bug Fix for the Default theme on the Function Settings page

 Bug fix for the Function Defaults screen and Function Settings page

---

EngineDriver/src/main/java/jmri/enginedriver/logviewer/ui/LogViewerActivity.java
EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_semi_realistic.java
EngineDriver/src/main/java/jmri/enginedriver/turnouts.java
EngineDriver/src/main/res/layout/throttle_semi_realistic_left.xml
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-cs/strings.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-pt/strings.xml
EngineDriver/src/main/res/values/strings.xml

* Bug fix for Sem-Realistic Throttle
* Fix mistake in the translations
* Linting

Bug fix for Sem-Realistic Throttle + other bug fixes

---

EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/import_export/ImportExportPreferences.java
EngineDriver/src/main/java/jmri/enginedriver/import_export/importServerManualEditTextPreference.java
EngineDriver/src/main/java/jmri/enginedriver/power_control.java
EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_full.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_semi_realistic.java
EngineDriver/src/main/java/jmri/enginedriver/type/pref_import_type.java
EngineDriver/src/main/res/layout/power_control.xml
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values/arrays.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/xml/preferences.xml
build.gradle
changelog-and-todo-list.txt

* Update to Gradle 8.4.2
* Clean-up of the Power screen

 * Update to Gradle 8.4.2 + Clean-up of the Power screen

---

EngineDriver/src/main/AndroidManifest.xml
EngineDriver/src/main/assets/about_page-ja.html
EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/res/values-ca/arrays.xml
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-cs/arrays.xml
EngineDriver/src/main/res/values-cs/strings.xml
EngineDriver/src/main/res/values-de/arrays.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-es/arrays.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-fr/arrays.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/arrays.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-ja/arrays.xml
EngineDriver/src/main/res/values-ja/strings.xml
EngineDriver/src/main/res/values-pt/arrays.xml
EngineDriver/src/main/res/values-pt/strings.xml
EngineDriver/src/main/res/values/arrays.xml
EngineDriver/src/main/res/values/bool.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/xml/preferences.xml
changelog-and-todo-list.txt

* Additional left/right swipe option to Increase/Decrease speed
* More of the French Canadian translations by Yvéric Patry (incomplete)
* Initial Google Japanese translations

Additional left/right swipe option to Increase/Decrease speed

---

EngineDriver/src/main/AndroidManifest.xml
EngineDriver/src/main/java/jmri/enginedriver/comms/comm_thread.java
EngineDriver/src/main/java/jmri/enginedriver/type/swipe_up_down_option_type.java
EngineDriver/src/main/java/jmri/enginedriver/util/HorizontalSeekBar.java
EngineDriver/src/main/java/jmri/enginedriver/util/VerticalSeekBar.java
EngineDriver/src/main/res/drawable/colorful_button_fn_layers_selected.xml
EngineDriver/src/main/res/drawable/colorful_button_layers_selected.xml
EngineDriver/src/main/res/drawable/colorful_button_layers_selected2.xml
EngineDriver/src/main/res/drawable/neon_button_fn_layers_selected.xml
EngineDriver/src/main/res/drawable/neon_button_layers_selected.xml
EngineDriver/src/main/res/drawable/original_button_layers_activated.xml
EngineDriver/src/main/res/drawable/original_button_layers_selected.xml
EngineDriver/src/main/res/drawable/original_progress_bar.xml
EngineDriver/src/main/res/drawable/transparent_progress_bar.xml
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-fr-rCA/strings.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-ja/strings.xml
EngineDriver/src/main/res/values-pt/strings.xml
EngineDriver/src/main/res/values/colors.xml
EngineDriver/src/main/res/values/dimen.xml
EngineDriver/src/main/res/values/themes.xml

* fix for a bug in the custom seekbar rendering on Android <=4.4
* fix for a bug in the custom button rendering on Android <=4.4
* More of the French Canadian translations by Yvéric Patry (incomplete)
* NPE bug fix.  still not sure how in happens

Fix for: swipe up down speed change. And seekbar on Android <=4.4

---

EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_original.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_semi_realistic.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_simple.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_switching_horizontal.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_switching_left_or_right.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_vertical_left_or_right.java
EngineDriver/src/main/res/layout/throttle.xml
EngineDriver/src/main/res/layout/throttle_switching_horizontal.xml

* rename yet another annoyingly abbreviated variable.

* fix webvew for the horizontal layouts.

---

EngineDriver/src/main/AndroidManifest.xml
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_original.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_switching_horizontal.java
EngineDriver/src/main/java/jmri/enginedriver/type/swipe_up_down_option_type.java
EngineDriver/src/main/res/values-ca/arrays.xml
EngineDriver/src/main/res/values-cs/arrays.xml
EngineDriver/src/main/res/values-de/arrays.xml
EngineDriver/src/main/res/values-es/arrays.xml
EngineDriver/src/main/res/values-fr/arrays.xml
EngineDriver/src/main/res/values-it/arrays.xml
EngineDriver/src/main/res/values-ja/arrays.xml
EngineDriver/src/main/res/values-pt/arrays.xml
EngineDriver/src/main/res/values/arrays.xml
changelog-and-todo-list.txt

don't change the volume select throttle on speed slider or buttons presses.

 don't change the volume select throttle on speed slider or buttons presses.

---

EngineDriver/src/main/assets/about_page-ca.html
EngineDriver/src/main/assets/about_page-cs.html
EngineDriver/src/main/assets/about_page-de-rAT-CH-LI.html
EngineDriver/src/main/assets/about_page-de.html
EngineDriver/src/main/assets/about_page-es.html
EngineDriver/src/main/assets/about_page-fr.html
EngineDriver/src/main/assets/about_page-ja.html
EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/res/values-ca/arrays.xml
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-cs/arrays.xml
EngineDriver/src/main/res/values-cs/strings.xml
EngineDriver/src/main/res/values-de/arrays.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-es/arrays.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-fr/arrays.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/arrays.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-ja/arrays.xml
EngineDriver/src/main/res/values-ja/strings.xml
EngineDriver/src/main/res/values-pt/arrays.xml
EngineDriver/src/main/res/values-pt/strings.xml
EngineDriver/src/main/res/values/strings.xml

* Added up/down swipe options to change the selected loco (volume) to the next available
* Additional Google translations

Added up/down swipe options to change the selected loco (volume) to the next available

---

EngineDriver/src/main/assets/about_page-ca.html
EngineDriver/src/main/assets/about_page-cs.html
EngineDriver/src/main/assets/about_page-de-rAT-CH-LI.html
EngineDriver/src/main/assets/about_page-de.html
EngineDriver/src/main/assets/about_page-es.html
EngineDriver/src/main/assets/about_page-fr.html
EngineDriver/src/main/assets/about_page-ja.html
EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/res/values-ca/arrays.xml
EngineDriver/src/main/res/values-cs/arrays.xml
EngineDriver/src/main/res/values-de/arrays.xml
EngineDriver/src/main/res/values-es/arrays.xml
EngineDriver/src/main/res/values-fr-rCA/strings.xml
EngineDriver/src/main/res/values-fr/arrays.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/arrays.xml
EngineDriver/src/main/res/values-ja/arrays.xml
EngineDriver/src/main/res/values-pt/arrays.xml
EngineDriver/src/main/res/values/arrays.xml

* Added shake action option for Emergency Stop
* Additional French Canadian translations by by Yvéric Patry (incomplete)

Added shake action option for Emergency Stop

---

EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
EngineDriver/src/main/java/jmri/enginedriver/comms/comm_handler.java
EngineDriver/src/main/java/jmri/enginedriver/comms/comm_thread.java
EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_semi_realistic.java
EngineDriver/src/main/java/jmri/enginedriver/type/stop_button_type.java
EngineDriver/src/main/java/jmri/enginedriver/util/PermissionsHelper.java
EngineDriver/src/main/java/jmri/enginedriver/util/VerticalSeekBar.java
EngineDriver/src/main/res/layout/throttle_semi_realistic_left.xml
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-cs/strings.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-fr-rCA/strings.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-ja/strings.xml
EngineDriver/src/main/res/values-pt/strings.xml
EngineDriver/src/main/res/values/arrays.xml
EngineDriver/src/main/res/values/bool.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/xml/preferences.xml
changelog-and-todo-list.txt

- Significant changes the to the Semi-Realistic Throttle, and in particular, the integration with decoders, with assistance from John Geddes
- Significant re-write of the air brake system in the Semi-Realistic Throttle

Significant changes to the Semi-Realistic Throttle

---

EngineDriver/src/main/java/jmri/enginedriver/comms/comm_thread.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/res/layout/part_function_buttons_vertical_one_column_0.xml
EngineDriver/src/main/res/layout/part_function_buttons_vertical_one_column_1.xml
EngineDriver/src/main/res/layout/part_function_buttons_vertical_one_column_2.xml
EngineDriver/src/main/res/layout/part_function_buttons_vertical_one_column_3.xml
EngineDriver/src/main/res/layout/part_function_buttons_vertical_one_column_4.xml
EngineDriver/src/main/res/layout/part_function_buttons_vertical_one_column_5.xml
EngineDriver/src/main/res/layout/part_function_buttons_vertical_two_columns_0.xml
EngineDriver/src/main/res/layout/throttle_vertical.xml
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-fr-rCA/strings.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-pt/strings.xml
changelog-and-todo-list.txt

* fix bug where the bottom of the last function was chopped off in the scroll region
* play a tone and vibrate when a system alert/message is received.
* fix bug where DCC-EX Routes and Turnouts may not load if ED is not removed from memory by Android

DCC-EX Routes and Turnouts may not load

---

EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/comms/comm_handler.java
EngineDriver/src/main/java/jmri/enginedriver/comms/comm_thread.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
changelog-and-todo-list.txt

identify serverType IoTT and send <U DISCONNECT>

send additional resync requests after EX reconnect

---

EngineDriver/src/main/java/jmri/enginedriver/comms/comm_thread.java

some linting in comm_thread, disabled set-labels start logging

removed leading zero from FKey id when sending

---

EngineDriver/src/main/assets/about_page-ca.html
EngineDriver/src/main/assets/about_page-cs.html
EngineDriver/src/main/assets/about_page-de-rAT-CH-LI.html
EngineDriver/src/main/assets/about_page-de.html
EngineDriver/src/main/assets/about_page-es.html
EngineDriver/src/main/assets/about_page-fr-rCA.html
EngineDriver/src/main/assets/about_page-fr.html
EngineDriver/src/main/assets/about_page-ja.html
EngineDriver/src/main/assets/about_page.html
EngineDriver/src/main/java/jmri/enginedriver/comms/comm_thread.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-cs/strings.xml
EngineDriver/src/main/res/values-de/strings.xml
EngineDriver/src/main/res/values-en-rAU/strings.xml
EngineDriver/src/main/res/values-en-rGB/strings.xml
EngineDriver/src/main/res/values-en-rNZ/strings.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-ja/strings.xml
EngineDriver/src/main/res/values-pt/strings.xml
EngineDriver/src/main/res/values/bool.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/xml/preferences.xml
changelog-and-todo-list.txt

- Added option to sequence the loading of items on DCC-EX
- Bug fix for Immersive mode. Particularly the button to show/hide the throttle web view.

- Added option to sequence the loading of items on DCC-EX

---

EngineDriver/src/main/java/jmri/enginedriver/logviewer/ui/LogViewerActivity.java
EngineDriver/src/main/java/jmri/enginedriver/type/message_type.java
changelog-and-todo-list.txt

replace the deprecated AsyncTask in LogViewer

---

.gitignore
EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
EngineDriver/src/main/java/jmri/enginedriver/import_export/ImportExportConnectionList.java
EngineDriver/src/main/java/jmri/enginedriver/import_export/ImportExportPreferences.java
EngineDriver/src/main/java/jmri/enginedriver/intro/intro_activity.java
EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_semi_realistic.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_switching_horizontal.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_switching_left_or_right.java
EngineDriver/src/main/java/jmri/enginedriver/type/acceleratorometer_action_type.java
EngineDriver/src/main/java/jmri/enginedriver/type/direction_type.java
EngineDriver/src/main/java/jmri/enginedriver/type/speed_step_type.java
EngineDriver/src/main/java/jmri/enginedriver/type/sub_activity_type.java
EngineDriver/src/main/java/jmri/enginedriver/web_activity.java
changelog-and-todo-list.txt

- Replace deprecated functions in Throttle, ImportExportConnectionsList and LogViewerActivity
- linting
- tidy up some code

- Replace deprecated functions in several files

---

EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
EngineDriver/src/main/res/layout/select_loco.xml

- Hopefully will prevent an issue seen on some phones.

Rework of the method selection checking on the Select Loco page

---

EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
EngineDriver/src/main/res/drawable/colorful_button_fn_layers_enabled.xml
EngineDriver/src/main/res/drawable/colorful_button_fn_layers_selected.xml
EngineDriver/src/main/res/drawable/colorful_button_layers_activated.xml
EngineDriver/src/main/res/drawable/colorful_button_layers_activated2.xml
EngineDriver/src/main/res/drawable/colorful_button_layers_activated_hovered.xml
EngineDriver/src/main/res/drawable/colorful_button_layers_activated_hovered2.xml
EngineDriver/src/main/res/drawable/colorful_button_layers_enabled.xml
EngineDriver/src/main/res/drawable/colorful_button_layers_enabled2.xml
EngineDriver/src/main/res/drawable/colorful_button_layers_hovered.xml
EngineDriver/src/main/res/drawable/colorful_button_layers_hovered2.xml
EngineDriver/src/main/res/drawable/colorful_button_layers_selected.xml
EngineDriver/src/main/res/drawable/colorful_button_layers_selected2.xml
EngineDriver/src/main/res/drawable/colorful_button_stop_layers_enabled.xml
EngineDriver/src/main/res/drawable/colorful_button_stop_layers_selected.xml
EngineDriver/src/main/res/values/colors.xml
EngineDriver/src/main/res/values/dimen.xml
changelog-and-todo-list.txt

Tweaking of the Colourful theme to make the buttons more three dimensional

Tweaking of the Colourful theme to make the buttons more three dimensional

---

EngineDriver/src/main/java/jmri/enginedriver/throttle_semi_realistic.java
EngineDriver/src/main/res/drawable/neon_button_fn_layers_selected.xml
EngineDriver/src/main/res/drawable/neon_button_layers_selected.xml
EngineDriver/src/main/res/drawable/original_button_layers_selected.xml
EngineDriver/src/main/res/values/colors.xml
EngineDriver/src/main/res/values/strings.xml
changelog-and-todo-list.txt

- bug fix for the SRT. "None" for the decoder type was being ignored.
+ more style tweaks

bug fix for the SRT

---

EngineDriver/src/main/java/jmri/enginedriver/throttle.java

removing an annoyance if you use the hide function buttons feature.  Particularly noticeable on the MC 2/Pro

Automatically change the 'volume throttle' if you use the select loco for that throttle.

---

EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/throttle_semi_realistic.java
EngineDriver/src/main/res/layout/preference_dialog_layout_decoder_functions.xml
EngineDriver/src/main/res/layout/preference_dialog_layout_number_unsigned_decimal_length_5.xml
EngineDriver/src/main/res/layout/preference_dialog_layout_number_unsigned_integer_length_2.xml
EngineDriver/src/main/res/layout/preference_dialog_layout_number_unsigned_integer_length_3.xml
EngineDriver/src/main/res/layout/preference_dialog_layout_number_unsigned_integer_length_4.xml
EngineDriver/src/main/res/layout/preference_dialog_layout_number_unsigned_integer_length_5.xml
EngineDriver/src/main/res/layout/throttle_semi_realistic_left.xml
EngineDriver/src/main/res/values-ca/arrays.xml
EngineDriver/src/main/res/values-cs/arrays.xml
EngineDriver/src/main/res/values-de/arrays.xml
EngineDriver/src/main/res/values-es/arrays.xml
EngineDriver/src/main/res/values-fr/arrays.xml
EngineDriver/src/main/res/values-it/arrays.xml
EngineDriver/src/main/res/values-ja/arrays.xml
EngineDriver/src/main/res/values-pt/arrays.xml
EngineDriver/src/main/res/values/arrays.xml
EngineDriver/src/main/res/xml/preferences.xml
changelog-and-todo-list.txt

- Preference screen numeric input dialogs show the keypad not the full keyboard
- ESU MC2/Pro fixes to support the SRT

Preference screen numeric input dialogs show the keypad not the full keyboard

---

EngineDriver/build.gradle
EngineDriver/src/main/java/jmri/enginedriver/ConsistEdit.java
EngineDriver/src/main/java/jmri/enginedriver/ConsistLightsEdit.java
EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
EngineDriver/src/main/java/jmri/enginedriver/about_page.java
EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/dcc_ex.java
EngineDriver/src/main/java/jmri/enginedriver/device_sounds_settings.java
EngineDriver/src/main/java/jmri/enginedriver/function_consist_settings.java
EngineDriver/src/main/java/jmri/enginedriver/function_settings.java
EngineDriver/src/main/java/jmri/enginedriver/gamepad_test.java
EngineDriver/src/main/java/jmri/enginedriver/logviewer/ui/LogViewerActivity.java
EngineDriver/src/main/java/jmri/enginedriver/power_control.java
EngineDriver/src/main/java/jmri/enginedriver/routes.java
EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
EngineDriver/src/main/java/jmri/enginedriver/throttle.java
EngineDriver/src/main/java/jmri/enginedriver/turnouts.java
EngineDriver/src/main/java/jmri/enginedriver/web_activity.java
EngineDriver/src/main/java/jmri/enginedriver/withrottle_cv_programmer.java
changelog-and-todo-list.txt
gradle.properties
originals/categories/category_esu_working.svg

* Update mimimumSDK to 36
- Required changes to hide soft keyboard
- Required changes to back button handling.  For unknown reasons some activities needed changing to compare to a static import.  Others did not. 
* Changed gradle.properties to disable parallel processes, as this repeatedly caused my PC to totally lock up (unable to even shutdown)

Update mimimumSDK to 36

---

EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
EngineDriver/src/main/java/jmri/enginedriver/logviewer/ui/LogViewerActivity.java
EngineDriver/src/main/res/layout/file_list_dialog.xml
EngineDriver/src/main/res/layout/file_list_item.xml
EngineDriver/src/main/res/values-ca/strings.xml
EngineDriver/src/main/res/values-cs/strings.xml
EngineDriver/src/main/res/values-de-rAT/strings.xml
EngineDriver/src/main/res/values-es/strings.xml
EngineDriver/src/main/res/values-fr/strings.xml
EngineDriver/src/main/res/values-it/strings.xml
EngineDriver/src/main/res/values-ja/strings.xml
EngineDriver/src/main/res/values-pt/strings.xml
EngineDriver/src/main/res/values/bool.xml
EngineDriver/src/main/res/values/strings.xml
EngineDriver/src/main/res/xml/preferences.xml

- Added a preference to immediately share any file from the ED scoped storage area
- Improved the file selection dialog for sharing

 Added preference to share any file from the ED scoped storage 

---

EngineDriver/src/main/java/jmri/enginedriver/intro/intro_permissions.java

- Missing code to support the permission requests in the new version of the intro screens

---

EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
changelog-and-todo-list.txt

- bug fix - notification going into background would not always show, particularly if ED had been restarted.
- bug fix - unable to click on notification to reopen on later versions of android

bug fixes - notification going into background 
