JMRI/EngineDriver

- res/values/bool.xml
- res/values/strings.xml
- res/xml/preferences.xml
- src/jmri/enginedriver/message_type.java
- src/jmri/enginedriver/preferences.java
- src/jmri/enginedriver/routes.java
- src/jmri/enginedriver/turnouts.java
Added a preference to omit a Turnout or Route from their respective list
if the username is missing or empty.  The preference defaults to true
for consistency with the current behavior.  If the preference is set to
false, all Turnouts and Routes are shown.
> New Pref to control display of Turnouts/Routes with no user name

- res/layout/throttle.xml
- res/values/bool.xml
- res/values/strings.xml
- res/xml/preferences.xml
- src/jmri/enginedriver/Consist.java
- src/jmri/enginedriver/connection_activity.java
- src/jmri/enginedriver/throttle.java
1 Decrease Loco No. button Height.  (Disabled by default)
2 Show loco address instead of names (Disabled by default)
3 Immersive mode. (Which to my surprise, works on a Jelly Bean phone) (Disabled by default)
4 Increase web view size (Disabled by default)
5 Stop on direction change while moving (Disabled by default)
6 "Always use default labels".  For the Function buttons, use the defaults instead of what is in the in the Roster (Disabled by default)
Notes:
3 force disables/ignores the 'Auto Connect' preference, as you can't get to the preferences (or eStop button) from the Throttle page when it is enabled.  (To allow you to get to the preferences before you connect.)   To get to the back button when in immersive mode, swipe up from the bottom of the screen.
5 If set, it overrides the …
> Numerous small Changes to the Throttle Preferences and Functionality

- res/values/strings.xml
- src/jmri/enginedriver/connection_activity.java
- src/jmri/enginedriver/throttle.java
- Enter and exit immersive mode (if enabled) by swiping down on any part of any Loco View (most of the screen)
- created new functions for entering an exiting immersive mode
- removed the old code related to the speed text
- added the new gesture for entering and exiting immersive mode
- added a toast message when you swipe down to exit immersive mode.
> Experimental - Change to the way of temporarily entering or exiting immersive mode 

- res/values/strings.xml
- src/jmri/enginedriver/throttle.java
- Improved enter and exit immersive mode (if enabled) by swiping down almost on any part of any Loco View (most of the screen, excluding the sliders and the title bar.)
- Fix - bug was causing swipes to be ignored in the slider areas, even when the sliders were hidden
- Fix - Mistake in the calculation of the top of the sliders. The bug was causing swipes to be ignored over a substantial amount of the screen that was not part of the sliders.
> Experimental - Immersive Mode  + some bug fixes

- src/jmri/enginedriver/throttle.java
Modification - Enable and disable the Direction and Loco buttons if the speed is greater than zero, and the preference for not allowing direction change while moving is set.
This currently doesn't work for the speed sliders, so the buttons remain enabled, but the toast message shows.
> Modification - Enable and disable the Direction and Loco buttons if the speed is greater than zero

- res/values/strings.xml
- src/jmri/enginedriver/throttle.java
Until I know more about the behaviour of Immersive Mode on Lollipop I think it is best to disable it.
(That was supposed to be Marshmallow not KitKat)
> Modification - Increased the minimum requirement for Immersive Mode to Android KitKat

- res/values/bool.xml
- res/values/strings.xml
- res/xml/preferences.xml
- src/jmri/enginedriver/throttle.java
NOTE: Currently only supports simple gamepads using 
iOS 'NewGame' mode - DPAD + keys:- Stop:y F0:h F1:u F2:j eStop:v 
or iOS 'iCade' mode - DPAD + keys:- Stop:3 F0:1 F1:2 F2:4 eStop:0
Only been able to test with one of these...
http://www.ebay.com.au/itm/Wireless-Bluetooth-Selfie-Remote-Controller-Shutter-Gamepad-For-IOS-Android-A-E0-/322586771955?hash=item4b1bab81f3:g:yYAAAOSwMVdYEcV6
> 	Experimental - basic gamepad support

- res/values/arrays.xml
- res/values/bool.xml
- res/values/strings.xml
- res/xml/preferences.xml
- src/jmri/enginedriver/throttle.java
Changed the preference so that you select exactly which type of gamepad mode to support.
NOTE: Currently only supports simple gamepads using 'MKT' mode or iOS 'iCade' mode
Only been able to test with one of these...
http://www.ebay.com.au/itm/Wireless-Bluetooth-Selfie-Remote-Controller-Shutter-Gamepad-For-IOS-Android-A-E0-/322586771955?hash=item4b1bab81f3:g:yYAAAOSwMVdYEcV6
> Experimental - basic gamepad support

- .gitignore
Android Studio creates a /out/production/EngineDriver folder under the
project and populates it with the resources, classes, etc.  This change
adds /out/ to gitignore.
> Ignore /out folder and subfolders

- src/jmri/enginedriver/throttle.java
The button press for functions was handled correctly, with the press
sent to all locos in the consist except for leadOnly functions.  However
the button release for functions was only being sent to the Lead loco
regardless of whether or not the function was leadOnly.  Corrected the
code for the release so it matches the code for the press - the release
is now sent to all locos unless the function is leadOnly.
> Correct function button release handling for consists

- res/values/arrays.xml
- res/values/integers.xml
- src/jmri/enginedriver/throttle.java
Following a screen rotation, the Direction button states weren't
restored until an update is received from WiT.  Code now saves the
Requested Direction values in the bundle so the Direction button states
can be restored immediately.
Button states are cleared when Menu or Status/Notification bar
is accessed (observed in Android 7.1.2).  Code now restores the Function button states when the Menu
or Status bar is exited and the Throttle screen gets the focus back.
> Preserve throttle button states

- res/values/arrays.xml
- src/jmri/enginedriver/throttle.java
Prevent assigning Volume to inactive throttle via touch action.  Move
Volume to next throttle if current Volume throttle consist is released.
Removed sleep() from SetNextThrottle method (because it runs on UI
thread).
> Volume throttle fixes

- res/values/arrays.xml
- res/values/strings.xml
- src/jmri/enginedriver/routes.java
- src/jmri/enginedriver/throttle.java
- src/jmri/enginedriver/turnouts.java
Corrected handling of start and end of gesture when the screen is locked
to fix a case where the screen could not be unlocked.
Changed gestureEnd so that left/right and up/down swipes are now
mutually exclusive. Swipes/flings are now processed for whichever
direction has the largest delta., which hopefully will suppress some
observed swipe anomalies.
Minor changes to a few pref strings.
> Screenlock fixes, Swipe/Fling direction selection

- res/values/strings.xml
- res/xml/preferences.xml
- src/jmri/enginedriver/ConsistEdit.java
- src/jmri/enginedriver/preferences.java
- src/jmri/enginedriver/select_loco.java
- src/jmri/enginedriver/throttle.java
Added Gamepad speed button repeat handling so now the effective repeat
rate and speed step size are the same as for the Increase/Decrease speed
buttons.  Previously the only option was the repeat rate generated by
the Gamepad itself, which I found was too high.  (For safety the Gamepad
speed autorepeat uses a separate (but similar) mechansim from the screen
Up/Down keys, although this could be revisited later.)
Added more audible Gamepad keypress sound feedback by using the
ToneGenerator instead of playing the SoundEffect CLICK.  The sound
generation is now encapsulated to make future changes easier.  A
different tone is used when Throttle hits hi/lo limits or on an invalid
press (for instance Next Throttle is pressed when only one throttle is
active).  The feedback volume level will …
> New Gamepad repeat handling and sound feedback.  Activity result defined.  Some code refactoring.

- src/jmri/enginedriver/throttle.java
Gamepad dispatchKeyEvent method was "swallowing" keypresses that did not
pertain to ED.  Unfortunately this included the MENU button on older
devices.  Changed code so that all keypresses not in the gamePadKeys[]
are passed to the super for processing.
Changed code so repeat count is processed for each individual
gamePadKeys[] value rather than for all keys at once.  Similar to the
change above, this allows repeat to flow through for keys not in
gamePadKeys[].
changeDirectionIfAllowed() now returns a boolean indicating whether the
throttle direction matches the requested direction.  Gamepad uses this
return value to generate the "NACK" audio feedback tone on a throttle
direction that isn't honored (due to preference settings and current
speed).
> Gamepad fixes, NACK tone on failed direction request

- src/jmri/enginedriver/preferences.java
- src/jmri/enginedriver/threaded_application.java
- src/jmri/enginedriver/throttle.java
Disable Gamepad Preferences menu if pre-KitKat and remove Android
version check from whichGamePad().
If more than 3 GamePads, treat extras as if GamePad 0.
> Gamepad minor updates

- src/jmri/enginedriver/Consist.java
- src/jmri/enginedriver/select_loco.java
- Only clear the Recent Locomotive List on a second click + an instruction on the first click that they need to click again.  (Reduced chance of accidentlly clearing the list when not intended.)
- Pay attention to the show dcc address instead of name preference.
> Select Loco - small changes

- src/jmri/enginedriver/throttle.java
- swap the gamepad to next available throttle if the loco on the currently throttle is released.
- fixed handling of the gamepad number indicators when the loco on the currently assigned throttle is released.
- improved seperation of touch events when a gamepad is not assigned to any throttle (none available to swap to)
> Multiple Gamepad support

- src/jmri/enginedriver/throttle.java
Addition - Volume keys respect the 'Speed button repeat delay' preference
Fix - repeat not working for the 'decrease speed' button
Fix - changes recomended by AndroidStudio 3. (they now produce errors) add 'View.'
> Volume keys respect the 'Speed button repeat delay' preference

- src/jmri/enginedriver/throttle.java
Fix - engage autorepeat immediately on the Gamepad speed buttons
Fix - engage autorepeat immediately on the Volume keys
Fix - ignore volume keys and the back button when evaluating if  akeystroke came from a gamepad (always treat them as having come from the phone itself regardless)
> Fix - engage autorepeat immediately 

- src/jmri/enginedriver/throttle.java
The setting was not being restored on all conditions
>  fix - restore auto-brightness / adaptive brightness setting when un-dimmed  

- res/values/strings.xml
- src/jmri/enginedriver/preferences.java
fix - Overwrite of file not working. (Was actually overwriting the default export file.)
new - Ignore blank host names.
change - option only available when there is no current connection (i.e when opened from the connections page)
> fix+change - option to MANUALLY save/restore preferences for a specific host

- res/values/arrays.xml
- res/values/integers.xml
- res/values/strings.xml
- res/xml/preferences.xml
- src/jmri/enginedriver/preferences.java
- src/jmri/enginedriver/throttle.java
NEW - support Magicsee R1 gamepad - Mode B  
(e.g. https://www.ebay.com.au/itm/NEW-Mini-Bluetooth-Remote-Controller-Wireless-Gamepad-for-Mobile-Phone-3D-VR-XR/122876742616?hash=item1c9c064bd8:g:kAQAAOSwBD9ZlWxO )
FIX - the previous gamepad fix to ignore the volume keys will stop the VR BOX gamepads from working correctly.  Now works out if the event comes from an internal or external device.
> fix+new - Magicsee R1 gamepad support + fix

- res/menu-v11/connection_menu.xml
- res/menu-v11/routes_menu.xml
- res/menu-v11/turnouts_menu.xml
- res/menu-v11/web_menu.xml
This changes menus for API 11 devices upwards to no longer include blank entries.
> Remove blank menu entries for API 11 onwards

- AndroidManifest.xml
- assets/about_page.html
- changelog-and-todo-list.txt
- res/values-en-rGB/strings.xml
- res/values/strings.xml
- src/jmri/enginedriver/preferences.java
- src/jmri/enginedriver/throttle.java
This improves the handling when the ESU MobileControl II is in stop mode.
It disables speed changes, blocks on-device button presses, disables loco selection and disables switch of controlled throttle. Suitable toast messages are displayed when attempting to perform these tasks.
Also included is some British English translations (only one string right now as the rest seem fine for me)
> Improve handling of ESU MCII stop mode

- src/jmri/enginedriver/ConsistEdit.java
- src/jmri/enginedriver/ConsistLightsEdit.java
- src/jmri/enginedriver/about_page.java
- src/jmri/enginedriver/connection_activity.java
- src/jmri/enginedriver/function_settings.java
- src/jmri/enginedriver/power_control.java
- src/jmri/enginedriver/preferences.java
- src/jmri/enginedriver/reconnect_status.java
- src/jmri/enginedriver/routes.java
- src/jmri/enginedriver/select_loco.java
- src/jmri/enginedriver/threaded_application.java
- src/jmri/enginedriver/throttle.java
- src/jmri/enginedriver/turnouts.java
- src/jmri/enginedriver/web_activity.java
This is an alternate solution to the theme switcher prompted by #141 as I noticed the same bunch of conditionals being repeated in essentially every activity class.
By refactoring these into one single method allows the conditional to only be maintained once meaning that any future additional themes need only be checked for in that one place rather than multiple.
Use of this could also allow us to permit theme changes without exiting the app.
> Refactor theme switcher to single shared method

- assets/about_page.html
- res/color/btn_text_states.xml
- res/color/btn_text_states_outline.xml
- res/color/btn_text_states_stop_btn_outline.xml
- res/color/fn_btn_text_states_outline.xml
- res/drawable/fn_button_states_round_outline.xml
- res/drawable/sticky_button_states.xml
- res/drawable/sticky_button_states_round.xml
- res/drawable/sticky_button_states_round_outline.xml
- res/values/arrays.xml
- res/values/bool.xml
- res/values/strings.xml
- res/xml/preferences.xml
- src/jmri/enginedriver/connection_activity.java
- src/jmri/enginedriver/function_button.java
- src/jmri/enginedriver/throttle.java
CHANGE - long press on either direction button now swaps direction but not the direction.
CHANGE - user editable text for the direction keys
BUG - Button Press Style still not correct
I can't figure this out.  The styling appears to be correct when I debug it, but not when I run it normally.
When I watch it in the debugger...
On a direction button press the showDirectionRequest() function is called directly which changes the button style (pressed + italic).
Then the Throttle receives two messages. The first message is the reverse to the direction of whatever you touched (Forward if you clicked Reverse, and vice versa).
The second message is the same as whatever you touched.  So it sets the button to pressed, then not presssed, then pressed.
If it is done slowly in the debugger it seems to …
> CHANGED - Optional alternate labels for the throttle direction buttons

- AndroidManifest.xml
- assets/about_page.html
- bin/AndroidManifest.xml
- res/layout/gamepad_test.xml
- res/menu/gamepad_test.xml
- res/menu/throttle_menu.xml
- res/values/bool.xml
- res/values/strings.xml
- res/xml/preferences.xml
- src/jmri/enginedriver/gamepad_test.java
- src/jmri/enginedriver/preferences.java
- src/jmri/enginedriver/threaded_application.java
- src/jmri/enginedriver/throttle.java
FIX - Swipe up Screen dimming for older Android.  Mimimum level set to 1
Gamepad testing screen is availble from the Throttle Screen menu for now, but will be moved later.
> NEW - Gamepad testing screen added

- AndroidManifest.xml
- src/jmri/enginedriver/gamepad_test.java
- src/jmri/enginedriver/threaded_application.java
- src/jmri/enginedriver/throttle.java
@flash62au the change in throttle.java prevents a crash on my 4.4.4 device, where data is null. This results in the test results not being recorded, and therefore testing keeps repeating, until I turn off "Enforce Gamepad Testing". I could not determine WHY data was null, data is not null when called for the ACTIVITY_SELECT_LOCO just above it.
Any idea what I'm missing regarding this?
>  avoid NPEs, update to -test7

- AndroidManifest.xml
- bin/AndroidManifest.xml
- res/layout/gamepad_test.xml
- res/values/strings.xml
- src/jmri/enginedriver/gamepad_test.java
- src/jmri/enginedriver/throttle.java
FIX - Gamepad Test page should now work on early version of Android
UPDATE - rearranged the Gamepad Test page so that it is shorter, and the centre section scrolls
UPDATE - Added skip and cancel buttons to the Gamepad Test page
UPDATE - re-added the the Gamepad Test menu option.  Can be invoked from the Throttle page at any time. This does not close automatically when complete. skip option revoved. Different help text. Cancel becomes close.
> UPDATE - Gamepad Test page

- src/jmri/enginedriver/gamepad_test.java
FIX - 'close' button on the preference version of the test page was being hidden (instead of the 'reset' button)
UPDATE - on the preference version of the test page, only the last button pressed is highlighted.
> FIX/UPDATE - gamepad test page

- src/jmri/enginedriver/threaded_application.java
make the order of the buttons on the Exit dialog the same on the new themes as it is on the Orginal theme.
> FIX - order of buttons on the Exit Dialog

- assets/about_page.html
- changelog-and-todo-list.txt
- src/jmri/enginedriver/throttle.java
Noticed that, on Estop, the knob wasn't reflecting the zero state.
This fixes that.
> Fix issue with MC2 knob position not updating on EStop

- src/jmri/enginedriver/throttle.java
After change brought in by #172 certain scenarios cause tracked throttle to be changed without user interaction.
Example is, after an Estop, the last throttle is selected even if that was not the one being controlled.
This fixes that behaviour whilst still allowing user-generated tracking to switch control.
Tested on ESU MC2
> Fix active throttle tracking on non-user generated events

- assets/about_page.html
- src/jmri/enginedriver/ImportExportPreferences.java
- src/jmri/enginedriver/connection_activity.java
- src/jmri/enginedriver/preferences.java
If the preferences are being imported into the same device that exported them, the throttle name is also imported.  This includes the automatic host based imports.
> CHANGE - Import includes Throttle name

- assets/about_page.html
- res/values/bool.xml
- res/values/strings.xml
- res/xml/preferences.xml
- src/jmri/enginedriver/gamepad_test.java
- src/jmri/enginedriver/throttle.java
NEW - new preference to skip gamepad test with just one 'decrease speed'
CHANGE - Remove TTS message when you change the Volume controlled Throttle
CHANGE - more tones played in the gamepad test screen
CHANGE - different TTS messages for different results from the gamepad test page
> CHANGES - TTS and Gamepad Testing

- res/values-it/strings.xml
- res/values-pt/strings.xml
- res/values/strings.xml
- res/xml/preferences.xml
- src/jmri/enginedriver/preferences.java
- src/jmri/enginedriver/throttle.java
Unticking 'Support Multiple Gamepads' disabled all gamepad support.
The option never had any code behind it so has never worked. As no one has found this before now, I have removed the option entirely.
> FIX - Multiple Gamepads Option

- assets/about_page.html
- changelog-and-todo-list.txt
- res/values-en-rAU/strings.xml
- res/values-en-rGB/strings.xml
- res/values-en-rNZ/strings.xml
- res/values/bool.xml
- res/values/strings.xml
- res/xml/preferences.xml
- src/jmri/enginedriver/throttle.java
This adds a new option for the ESU Mobile Control II to disable direction change at zero end-stop position.
Requested by Pete Mulvany
> option for ESU Mobile Control II to disable direction change

- assets/about_page.html
- changelog-and-todo-list.txt
- res/values/bool.xml
- res/values/strings.xml
- res/xml/preferences.xml
- src/jmri/enginedriver/throttle.java
This comes from a suggestion by Pete Mulvany to optimise operations where inadvertent short-presses can hamper operations.
The LED on the device will still change to Red when a short-press is detected but, when disabled, no action will be taken upon release.
A long-press (time of which is configurable) will always result in an action stopping all locos currently controlled by the device.
> Allow ESU MCII stop button short-press to be disabled

- AndroidManifest.xml
- assets/about_page.html
- bin/AndroidManifest.xml
- res/drawable/app_splash.xml
- res/values-it/arrays.xml
- res/values-it/strings.xml
- res/values-pt/arrays.xml
- res/values-pt/strings.xml
- res/values-v11/themes.xml
- res/values/arrays.xml
- res/values/strings.xml
- res/values/themes.xml
- res/xml/preferences.xml
- src/jmri/enginedriver/ConsistEdit.java
- src/jmri/enginedriver/ConsistLightsEdit.java
- src/jmri/enginedriver/LocaleHelper.java
- src/jmri/enginedriver/about_page.java
- src/jmri/enginedriver/connection_activity.java
- src/jmri/enginedriver/function_settings.java
- src/jmri/enginedriver/gamepad_test.java
- src/jmri/enginedriver/power_control.java
- src/jmri/enginedriver/preferences.java
- src/jmri/enginedriver/reconnect_status.java
- src/jmri/enginedriver/routes.java
- src/jmri/enginedriver/select_loco.java
- src/jmri/enginedriver/threaded_application.java
- src/jmri/enginedriver/throttle.java
- src/jmri/enginedriver/turnouts.java
- src/jmri/enginedriver/web_activity.java
NEW - Change language from inside the App
NEW - Load transparent Splash Screen  …
Load a transparent splash screen on start, before loading the chosen theme.
Stops the checkerplate bitmap from momentarily being displayed when you are using any of the non-default themes.
> NEW - Change language from inside the App

- AndroidManifest.xml
- assets/about_page.html
- bin/AndroidManifest.xml
no longer requires an accelerometer in the device to install from the Play Store (reported bug)
> FIX  - accelerometer in the device to install from the Play Store 

- res/values-it/strings.xml
- res/values-pt/strings.xml
- res/values/strings.xml
- src/jmri/enginedriver/preferences.java
I can't resolve the timing problem of the create and destroy on preference change, so I have restricted when the Throttle Screen Type can be selected to just the Connection Screen.
> FIX - crash when swtiching throttle types on old versions of Android

- src/jmri/enginedriver/preferences.java
- src/jmri/enginedriver/throttle.java
Solves one crash when you hold a gamepad button down at the same time you press the back button and exit the app.
> FIX - Crash when holding Gamepad button on Exit

- src/jmri/enginedriver/throttle.java
fix for a mistake in the indexes for the different arrays that represent the gamepads and the throttles the gamepads are assigned to.
> FIX - Gamepad not responding if throttle 1 is empty

- src/jmri/enginedriver/throttle.java
line of code missed during the array changes. Pointed out by R.Su.
> FIX - missed code

- src/jmri/enginedriver/preferences.java
The option will now be saved as 'None' so that when it imports it will be automatically set to 'None'.
Fresh start of the app will reset to 'None'.
Reload of an old save that did not save the 'None' will still set it incorrectly.  Timing issue I can't quite resolve yet.
Also fixed a mistake that allowed Web View preferences to be selected in 'Simple' throttle
> Partial FIX - Import Export not resetting to 'None'

- EngineDriver/src/main/java/jmri/enginedriver/Loco.java
- EngineDriver/src/main/java/jmri/enginedriver/throttle.java
- EngineDriver/src/main/res/values/arrays.xml
resolves a problem where a function button is pressed on a loco that is also part of a consist elsewhere, or where a function button is also matched, using the new rules, on a different function number on a loco in the same consist.
> FIX - only set function button state if the message relates to lead loco

- EngineDriver/src/main/java/jmri/enginedriver/util/Flashlight.java
This caters for running on hardware that has a camera, but no flash unit.
Until a cleaner way is found of identifying this situation, simply catches the exception otherwise thrown.
> Catch exception when running on hardware with flash-less camera

- EngineDriver/src/main/java/jmri/enginedriver/throttle.java
Crash Report 2 had an NPE apparently caused by a handler getting a
callback from a Post_Delayed after the handler was set to null in
onDestroy.  Added RemoveCallbacksandMessages() to onDestroy to try to
clean up any pending events.
> Attempt to mitigate handler NPE crash

- EngineDriver/src/main/java/jmri/enginedriver/preferences.java
'recreate()' seems to be a better way to restart the activity.
> CHANGE - cleaner way to recreate the Preference activity on Import or when hiding/showing the advanced preferences

- EngineDriver/src/main/java/jmri/enginedriver/throttle.java
Unless it is on the top level page
>  FIX - Back Button in Throttle webView does not cause ED to ask to close 

- EngineDriver/src/main/java/jmri/enginedriver/util/PermissionsHelper.java
When a permission is not granted, ShowRetry() called requestNecessaryPermissions() which uses activity.requestPermissions().  There was a @TargetApi annotation for 6.0 (M) on this method.  A user ran ED on Android 5.1 (Lollipop) got a NoSuchMethodError.  To accommodate this user I modified ShowRetry() to not call requestNecessaryPermissions() on pre-6.0 (Marshmallow).  Also changed the notation to @RequiredApi so usage will be flagged in red by AS.
> Handle lack of activity.requestPermissions() in older Android versions

- EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
Changed refresh_roster_list consist code to follow pattern used for locos - copy keyset into Array and then iterate over array - to avoid ConcurrentModificationException.
> prevent ConcurrentModificationException due to iterating over shared LinkedHashMap (report 3 package 2)

- EngineDriver/src/main/java/jmri/enginedriver/Consist.java
- EngineDriver/src/main/java/jmri/enginedriver/ConsistEdit.java
- EngineDriver/src/main/java/jmri/enginedriver/ConsistLightsEdit.java
- EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
- EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
Change roster_entries, consist_entries and ConLoco.con from
LinkedHashMap to Collections.synchronizedMap(LinkedHashMap) to avoid
concurrency issues when copying the maps for reading.  Note that if this
works it would then be good to test whether we can eliminate the copying
and just do the reading on the original instances of the maps.
> avoid concurrentmodification

- EngineDriver/src/main/java/jmri/enginedriver/ImportExportPreferences.java
- EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
- EngineDriver/src/main/java/jmri/enginedriver/util/SwipeDetector.java
- EngineDriver/src/main/res/layout/edit_recent_name.xml
- EngineDriver/src/main/res/values/strings.xml
For Recent Locos and Recent Consists
- Swipe L-R now used to remove from list
- Long press lets you rename the recent consist
- Long press lets you rename the recent loco
- Help Toast message to explain each
Import/Export saves/restores the consists
Import/Export saves/restores the loco names
> Recents - Swipe remove, long press rename, import/export

- EngineDriver/src/main/assets/about_page-ca.html
- EngineDriver/src/main/assets/about_page-cs.html
- EngineDriver/src/main/assets/about_page-de-rAT-CH-LI.html
- EngineDriver/src/main/assets/about_page-de.html
- EngineDriver/src/main/assets/about_page-es.html
- EngineDriver/src/main/assets/about_page-fr.html
- EngineDriver/src/main/assets/about_page.html
- EngineDriver/src/main/java/jmri/enginedriver/ImportExportPreferences.java
- EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
- EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
- EngineDriver/src/main/res/layout/connections_list_item.xml
- EngineDriver/src/main/res/layout/consists_list_item.xml
- EngineDriver/src/main/res/layout/engine_list_item.xml
- EngineDriver/src/main/res/values-ca/strings.xml
- EngineDriver/src/main/res/values-cs/strings.xml
- EngineDriver/src/main/res/values-de/strings.xml
- EngineDriver/src/main/res/values-es/strings.xml
- EngineDriver/src/main/res/values-fr/strings.xml
- EngineDriver/src/main/res/values-it/strings.xml
- EngineDriver/src/main/res/values-pt/strings.xml
- EngineDriver/src/main/res/values/strings.xml
Loco Selection
- Pick from roster - get roster name and roster function buttons
- Enter address - get address as the name and generic functions per Prefs
- Pick from recent locos - whichever was originally set, including the edited name (see below)
- Pick from recent consists - whichever was originally set, including the edited name (see below)
Recent Locos
- if loco was selected from the roster, long press get you roster details
- if loco was from an entered address, long press allows you to edit the name
Recent Consists
- allow you edit the name
General
- it remembers the correct loco if more than one with the same address
- if you edit the name of a recent, then re-enter the same address, it considers it to be different to the remembered one.
> Rework of Recent and Recent Consists

- EngineDriver/src/main/java/jmri/enginedriver/ConsistEdit.java
- EngineDriver/src/main/java/jmri/enginedriver/ImportExportPreferences.java
- EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
- EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
- EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
- EngineDriver/src/main/res/layout/consist_item.xml
- EngineDriver/src/main/res/values-ca/strings.xml
- EngineDriver/src/main/res/values-cs/strings.xml
- EngineDriver/src/main/res/values-de/strings.xml
- EngineDriver/src/main/res/values-es/strings.xml
- EngineDriver/src/main/res/values-fr/strings.xml
- EngineDriver/src/main/res/values-it/strings.xml
- EngineDriver/src/main/res/values-pt/strings.xml
- EngineDriver/src/main/res/values/strings.xml
- changelog-and-todo-list.txt
1) removed symbols in "Recent Locos" and "Recent Consists"
2) "Edit Order and Direction" and "Edit Lights" removed when only one loco has been selected.
4) After a Reset, suppress the "Recent Connection" toast help on the first page of the Intro.
7) Add "Direction" to the list header on the Consist Edit page
8) Consist Edit swipe not working
X) remove earlier parts of the consist as you are building it (fixed yet again)
Y) better handling older style file formats for the recent locos in server specific preferences
TBA
3) show the renamed consist name on the throttle page
> Recent Consists - fixes

- EngineDriver/src/main/java/jmri/enginedriver/ImportExportPreferences.java
- EngineDriver/src/main/java/jmri/enginedriver/message_type.java
- EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
- EngineDriver/src/main/java/jmri/enginedriver/throttle.java
- EngineDriver/src/main/java/jmri/enginedriver/turnouts.java
- re-working of when the Recent list is shown to stop it showing on the bottom of the defined list
- reduce how often the list is saved
- remove recent entries if the server responds with an error
FIX - start the Children's timer of vertical seek bar action
> FIX - Recent Turnouts

- EngineDriver/src/main/java/jmri/enginedriver/throttle.java
- EngineDriver/src/main/res/values-fr/strings.xml
When using the gamepad on the Switching/Shunting screen, play sounds correctly when the speed goes up through zero and down to 100% reverse
> FIX - Switching/Shunting screen gamepad sounds

- EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
On a CONNECT message, the TA comm_handler sets fastClockSeconds to 0.  However the handler code was opening the WiT socket first and then later setting fastClockSeconds to 0.   As a result it was possible that the WiT Socket handler could receive the initial PFT time update and set fastClockSeconds first, and then the CONNECT handler would set it back to 0.  To prevent this case from happening I rearranged the CONNECT message handler code so that it sets fastClockSeconds before opening the WiTSocket.
Also removed the use of time offset from getFastClockTime() since this routine now does its work in GMT and the offset is by definition 0.
> Initial fastclock value shown as 00:00

- EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
- EngineDriver/src/main/java/jmri/enginedriver/throttle.java
- EngineDriver/src/main/java/jmri/enginedriver/web_activity.java
Longclick on a webview now refreshes the display (reloads the webview).
Added host ip to safebrowsingwhitelist for API O_MR1 and later.
Removed legacy code related to loading a static url when pausing since the webview itself is now paused directly.
> webview longclick refresh, safe browsing whitelist 

- EngineDriver/src/main/AndroidManifest.xml
- EngineDriver/src/main/java/jmri/enginedriver/ImportExportPreferences.java
- EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
- EngineDriver/src/main/java/jmri/enginedriver/logviewer/ui/LogViewerActivity.java
- EngineDriver/src/main/java/jmri/enginedriver/preferences.java
- EngineDriver/src/main/java/jmri/enginedriver/routes.java
- EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
- EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
- EngineDriver/src/main/java/jmri/enginedriver/throttle.java
- EngineDriver/src/main/java/jmri/enginedriver/turnouts.java
- EngineDriver/src/main/java/jmri/enginedriver/web_activity.java
- EngineDriver/src/main/java/jmri/jmrit/roster/RosterLoader.java
Changed Web activity back to SingleTask. Webview state is preserved across rotations and navigation.
Webview handling in Web and Throttle activities improved. scale preserved properly.
Notifications are now handled in an ApplicationLifecycleHandler. Much cleaner code and no false notifications when rotating.
Explicitly close InputStream in RosterLoader.parse() and BufferedReader in LogViewerActivity.doInBackground.
> Web and background work, Stream close

- EngineDriver/src/main/java/jmri/enginedriver/throttle.java
- EngineDriver/src/main/java/jmri/enginedriver/web_activity.java
Previously an invalid initial web page preference (from a typo for instance) would result in continual reloading of the webpage.  The code now uses a loading retry counter  and stops after 3 attempts.
Noted that using onReceivedHttpError produced cleaner code but that callback is only available starting with SDK 23.  The implemented approach works with all supported SDK levels.
> Improve invalid initial web page preference handling

- EngineDriver/src/main/java/jmri/enginedriver/message_type.java
- EngineDriver/src/main/java/jmri/enginedriver/preferences.java
- EngineDriver/src/main/java/jmri/enginedriver/throttle.java
- EngineDriver/src/main/java/jmri/enginedriver/web_activity.java
Throttle and Web webviews were both getting reinitialized when either Initial Web Page preference was changed.  There is now a separate message for each preference change so that only the affected webview is reinitialized.
> Separate Throttle and Web initial webpage messages

- EngineDriver/src/main/java/jmri/enginedriver/ConsistEdit.java
- EngineDriver/src/main/java/jmri/enginedriver/ConsistLightsEdit.java
- EngineDriver/src/main/java/jmri/enginedriver/about_page.java
- EngineDriver/src/main/java/jmri/enginedriver/function_settings.java
- EngineDriver/src/main/java/jmri/enginedriver/gamepad_test.java
- EngineDriver/src/main/java/jmri/enginedriver/intro_activity.java
- EngineDriver/src/main/java/jmri/enginedriver/power_control.java
- EngineDriver/src/main/java/jmri/enginedriver/preferences.java
- EngineDriver/src/main/java/jmri/enginedriver/reconnect_status.java
- EngineDriver/src/main/java/jmri/enginedriver/routes.java
- EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
- EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
- EngineDriver/src/main/java/jmri/enginedriver/throttle.java
- EngineDriver/src/main/java/jmri/enginedriver/turnouts.java
- EngineDriver/src/main/java/jmri/enginedriver/web_activity.java
Reinitialize the web_activity statics if the Web initial webpage preference is changed while the web_activity is not open.  This will cause the new initial webpage to get loaded the next time the web_activity is opened.
> Reinit web_activity on pref change, remove legacy notification calls

- EngineDriver/src/main/java/jmri/enginedriver/ConsistEdit.java
- EngineDriver/src/main/java/jmri/enginedriver/ConsistLightsEdit.java
- EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
- EngineDriver/src/main/java/jmri/enginedriver/message_type.java
- EngineDriver/src/main/java/jmri/enginedriver/power_control.java
- EngineDriver/src/main/java/jmri/enginedriver/preferences.java
- EngineDriver/src/main/java/jmri/enginedriver/reconnect_status.java
- EngineDriver/src/main/java/jmri/enginedriver/routes.java
- EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
- EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
- EngineDriver/src/main/java/jmri/enginedriver/throttle.java
- EngineDriver/src/main/java/jmri/enginedriver/turnouts.java
- EngineDriver/src/main/java/jmri/enginedriver/web_activity.java
Changed the mechanism used when a Preference change (ex. theme change) necessitates a restart.  The new approach is basically to disconnect from WiT, close all activities and restart CA without ever exiting ED.
There is a new RESTART_APP message type associated with the change. If a restart is required then Prefs or Throttle sends this message to TA.  TA closed the WiT connection and then sends the message to all Activities.  Most activities treat this message the same as DISCONNECT.  Throttle or CA (whichever is alive) launch a new CA instance then finish.
> Revise restart mechanism following Preference change

- EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
- EngineDriver/src/main/java/jmri/enginedriver/throttle.java
New witSetSpeedZero(), witSetSpeed(), witRequestSpeed() and witRequestDir() methods eliminate coding the same wit message strings in multiple places.
> encapsulate a few WiT messages

- EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
Restart the outbound heartbeat on every successful send to WiT.  JMRI now sends speed and direction updates regardless of the source of the change for inuse engines so we don't need to rely on explicit periodic requests for speed and direction.
> outbound heartbeat restart

- EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
- EngineDriver/src/main/java/jmri/enginedriver/throttle.java
Previously continuous slider movement resulting in a very rapid speed request message stream to WiT, as quickly as every 10 milliseconds on my test device.  The change adds a pacing timer to limit speed requests to once every 200 milliseconds.
> Pace speed request messages to WiT

- EngineDriver/src/main/assets/about_page.html
- EngineDriver/src/main/java/jmri/enginedriver/throttle.java
- EngineDriver/src/main/java/jmri/enginedriver/throttle_switching_left_or_right.java
Sends the last speed value to WiT after the pacing delay expires if it hasn't already been sent.  This ensures WiT has the latest speed value.
> Ensure WiT gets final speed value

- EngineDriver/src/main/java/jmri/enginedriver/ConsistEdit.java
- EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
Adding error handling and diagnostics in ConsistEdit.onCreate to prevent reported crash.
Adding error handling and diagnostics in TA.throttleCharToInt to identify cases where the argument is invalid and to prevent returning negative values.
> Add error handling

- EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
Don't attempt to send a "Q" to WiT on exit unless the socket is good.  When there was no connection, this was producing a toast message on exit about failing to connect.
> Suppress WiT message on exit unless connected

- EngineDriver/src/main/java/jmri/enginedriver/ConsistEdit.java
- EngineDriver/src/main/java/jmri/enginedriver/ConsistLightsEdit.java
- EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
- EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
- EngineDriver/src/main/java/jmri/enginedriver/throttle.java
- EngineDriver/src/main/java/jmri/enginedriver/throttle_full.java
Added more tests for null consists and null consists[i] entries.
Added try/catch block in TA.initShared() to log any instance where consists and function arrays can't be instantiated.
Corrected logic in throttle.showHideConsistMenu().
Updated throttleCharToInt() for better debug error reporting, removed unused case statements and clarified code.
Revised throttle message handler so whichThrottle is only calculated when the message actually contains a whichThrottle value.  This suppresses error messages generated by throttleCharToInt from getting passed non-throttle values.
Commented out dead WiT 'R' case block in throttle message handler.
Simplified tests in WiT 'P' case block in throttle message handler.
> consists null debugging and fixes

- EngineDriver/src/main/java/jmri/enginedriver/throttle_full.java
Added consists[i] null checks to throttle screen apportionment code in set_labels.  Also revised that code to use mainapp.numThrottles rather than fetching and testing the "number of throttles" pref string value.
> consists null checks in set_labels

- EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
- EngineDriver/src/main/java/jmri/enginedriver/preferences.java
Hide preference if the hostname is not blank
Restart app on close of preferences
Clear hostname,ip,port in onCreate of CA
> Clean up of Force restart on change of the WiFi / Mobile Data preference

- EngineDriver/src/main/java/jmri/enginedriver/throttle.java
This deals with the edge-case where the linked command station changes the speedsteps setting for the currently controlled loco.
As a result, the app will no longer crash, rather ignore the knob position request.
> Avoid crashing when updating knob position if speed-steps changed

- EngineDriver/src/main/java/jmri/enginedriver/preferences.java
Brut force restart seemed to be needed to fully reload everything with the chosen language.
> Force the app to really restart on Localisation change

- EngineDriver/src/main/java/jmri/enginedriver/throttle.java
partly address problem when you use the switchThrottleScreen to go from a single throttle layout to a multiple throttle layout
> improve switchThrottleScreenType

- EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
FIX - Roster entry option did not show for earlier version of JMRI
Change to show the Roster Entry option the serverType is blank.
> FIX - Roster entry option did not show for earlier version of JMRI

- EngineDriver/src/main/res/values-en-rAU/strings.xml
- EngineDriver/src/main/res/values-en-rGB/strings.xml
- EngineDriver/src/main/res/values-en-rNZ/strings.xml
- EngineDriver/src/main/res/values/strings.xml
- EngineDriver/src/main/res/xml/preferences.xml
- significant 'things' capitalised in titles and summaries (eg. Throttle Screen, Web View, etc.)
- object of the preference capitalised  (e.g. Lights, Timeout, etc.)
- question mark after the title if a checkbox
- question marks removed from the summaries
- full stops (periods) removed from summaries unless more than one sentence
- "Show...", "Allow..." removed from some titles
- "Page" generally changed to "Screen" (i.e. not including "Web Page")
- small changes to some text
> Cleanup of the Preference titles and summaries

- EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
- EngineDriver/src/main/res/values/arrays.xml
Since the rework for the Toolbar:
1. the Advanced preferences have not been hidden correctly in the Sub-Preferences
2. the array now contained a lot of unnecessary entries
The top level preferences and the sub-preferences needed to be treated separately
> Fix - Rework of the Advanced Prefeences feature

- EngineDriver/src/main/AndroidManifest.xml
- EngineDriver/src/main/java/jmri/enginedriver/ImportExportConnectionList.java
- EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
- EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
- Android 4 does not have permission to Scoped Storage unless WRITE_EXTERNAL_STORAGE is also granted (which is ignored in all other versions)API update - Android 4 
This is not mentioned in any doco I found
> API update - Android 4 problem

- EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
- EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
- EngineDriver/src/main/java/jmri/enginedriver/throttle.java
- EngineDriver/src/main/res/layout/throttle_simple.xml
- EngineDriver/src/main/res/values/strings.xml
- add sounds options for the 'simple' layout
- clean up the wording for 'Web Screen' VS 'Throttle Web View
- stop automatically reloading the throttle page if the max/fixed number of throttles is different (now waits till the settings page is closed)
> Various fixes

- EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
- EngineDriver/src/main/java/jmri/enginedriver/device_sounds_settings.java
- EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
- EngineDriver/src/main/java/jmri/enginedriver/throttle.java
sample .ipls file format...
/ sample custom 'In-Phone Loco Sounds' (.ipls) file
/
/ - the first character of each line is the instruction/sound type
/ - Lines starting with "/" are comments
/ - Avoid additional spaces (it will try to trim leading and trailing spaces)
/   i.e don't put a space before or after the colon.
/ - this .ipls file MUST be placed in ../Android/data/jmri.enginedriver/files/
/ - By default, the sound files are expected to be in ../Android/data/jmri.enginedriver/files/
/   however you can put them in subfolders by prepending the sound file name with <folder name><forward slash>
/   e.g. sample/bell_start.mp3     - will look for ../Android/jmri.enginedriver/files/sample/bell_start.mp3
/ - The files used for the inbuilt sounds (and this sample) can be copied from here: …
> Support for custom (user defined) loco sounds

- EngineDriver/src/main/assets/about_page.html
- EngineDriver/src/main/java/jmri/enginedriver/gamepad_test.java
- EngineDriver/src/main/java/jmri/enginedriver/throttle.java
- EngineDriver/src/main/res/layout/gamepad_test.xml
- EngineDriver/src/main/res/values-fr/arrays.xml
- EngineDriver/src/main/res/values/arrays.xml
- EngineDriver/src/main/res/values/strings.xml
- changelog-and-todo-list.txt
- in prep for creating a Arduino gamepad controller
-----------------
Keyboard Commands
Up = Increase Speed
Down = Decrease Speed
'X' = Stop 
Left = Reverse (Forward if changed in preferences)
Right = Forward (Reverse if changed in preferences)
'D' = Direction - Toggle Forward/Reverse
'N' = Next Throttle
'Z' = All stop
F00 - F28 = Function
Must be 'F' followed by two digits
S000 - S100 = Speed
Must be 'S' followed by three digits
In Phone Loco Sounds (IPLS)
'B' = Bell
'H' = Horn / Whistle
'J' = Short Horn
'M' or Volume Mute = Mute IPLS
T0 - T5 = Specify a throttle for next command
Must be 'T' followed by one digit
The following command will sent to the specified throttle regardless of the currently selected gamepad throttle. 
All other keyCodes are ignored
Failure to follow the 'F', 'S' …
> Option to use a normal keyboard (bluetooth or USB) as a gamepad type

- EngineDriver/src/main/assets/about_page-ca.html
- EngineDriver/src/main/assets/about_page-cs.html
- EngineDriver/src/main/assets/about_page-de-rAT-CH-LI.html
- EngineDriver/src/main/assets/about_page-de.html
- EngineDriver/src/main/assets/about_page-es.html
- EngineDriver/src/main/assets/about_page-fr.html
- EngineDriver/src/main/assets/about_page.html
- EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
- EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
- EngineDriver/src/main/java/jmri/enginedriver/function_consist_settings.java
- EngineDriver/src/main/java/jmri/enginedriver/function_settings.java
- EngineDriver/src/main/java/jmri/enginedriver/logviewer/ui/LogViewerActivity.java
- EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
- EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
- EngineDriver/src/main/java/jmri/enginedriver/throttle.java
- EngineDriver/src/main/res/layout/roster_entry.xml
- EngineDriver/src/main/res/values-ca/strings.xml
- EngineDriver/src/main/res/values-cs/strings.xml
- EngineDriver/src/main/res/values-de/strings.xml
- EngineDriver/src/main/res/values-es/strings.xml
- EngineDriver/src/main/res/values-fr/strings.xml
- EngineDriver/src/main/res/values-it/strings.xml
- EngineDriver/src/main/res/values-pt/strings.xml
- EngineDriver/src/main/res/values/strings.xml
- changelog-and-todo-list.txt
- rewrite of the way the images are opened and compressed to support very large source images
- shift all the saved images to .PNG (from .JPG) to resolve the problem of the transparent backgrounds
- correctly applies rotation of the source image
- option to the remove the local image (roster images only)
> Local roster images

- EngineDriver/src/main/AndroidManifest.xml
- EngineDriver/src/main/assets/about_page.html
- EngineDriver/src/main/java/jmri/enginedriver/Consist.java
- EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
- EngineDriver/src/main/java/jmri/enginedriver/dcc_ex.java
- EngineDriver/src/main/java/jmri/enginedriver/message_type.java
- EngineDriver/src/main/java/jmri/enginedriver/routes.java
- EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
- EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
- EngineDriver/src/main/java/jmri/enginedriver/throttle.java
- EngineDriver/src/main/java/jmri/enginedriver/turnouts.java
- EngineDriver/src/main/java/jmri/enginedriver/util/comm_handler.java
- EngineDriver/src/main/java/jmri/enginedriver/util/comm_thread.java
- EngineDriver/src/main/res/layout/connection.xml
- EngineDriver/src/main/res/layout/dcc_ex.xml
- EngineDriver/src/main/res/layout/device_sounds_settings.xml
- EngineDriver/src/main/res/layout/select_loco.xml
- EngineDriver/src/main/res/menu/routes_menu.xml
- EngineDriver/src/main/res/menu/throttle_menu.xml
- EngineDriver/src/main/res/menu/turnouts_menu.xml
- EngineDriver/src/main/res/values/bool.xml
- EngineDriver/src/main/res/values/strings.xml
- EngineDriver/src/main/res/xml/preferences.xml
Optional use the DCC-EX commands rather then wiThrottle.  
And also allo CV programming on the programming track (in DCC-EX only).
comm_handler and comm_thread have been split out of T_A.
95% of the changes are in comm_thread.  The changes effectively act as a translator from DCC-EX to wiThrottle.
Instructions for use
- Enable the new preference in the "Connect Preference" group - "Use native DCC-EX commands"
- If you use other manufaturer's DCC systems, also enable the preference below it - "Show protocol option".  Enabling this will show a yes/no question at the bottom of the connection screen to allow you to switch between the wiThrottle and DCC-EX protocols easily
Only if you connect via the DCC-EX protocol... A new menu option will appear ("DCC-EX") after you connect, which allows CV …
> DCC-EX native command support

- EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
- EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
- EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
- EngineDriver/src/main/java/jmri/enginedriver/util/comm_thread.java
- EngineDriver/src/main/res/values/bool.xml
- EngineDriver/src/main/res/values/strings.xml
- EngineDriver/src/main/res/xml/preferences.xml
* option to allow the server to return the function labels of non-roster locos
* For DCC-EX, allow overriding of the default latching behaviour of all/any functions
> Option to allow the server to return the function labels of non-roster locos

- EngineDriver/src/main/java/jmri/enginedriver/Loco.java
- EngineDriver/src/main/java/jmri/enginedriver/throttle.java
- EngineDriver/src/main/java/jmri/enginedriver/util/comm_thread.java
prefAlwaysUseFunctionsFromServer did not work correctly in some circumstances, particularly (but not only) when the roster entry had all blank function labels.
> prefAlwaysUseFunctionsFromServer - Fixes

- EngineDriver/src/main/AndroidManifest.xml
- EngineDriver/src/main/java/jmri/enginedriver/Loco.java
- EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
- EngineDriver/src/main/java/jmri/enginedriver/function_consist_settings.java
- EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
- EngineDriver/src/main/java/jmri/enginedriver/throttle.java
- EngineDriver/src/main/java/jmri/enginedriver/util/comm_handler.java
- EngineDriver/src/main/java/jmri/enginedriver/util/comm_thread.java
- EngineDriver/src/main/res/values-ca/arrays.xml
- EngineDriver/src/main/res/values-cs/arrays.xml
- EngineDriver/src/main/res/values-de/arrays.xml
- EngineDriver/src/main/res/values-es/arrays.xml
- EngineDriver/src/main/res/values-fr/arrays.xml
- EngineDriver/src/main/res/values-it/arrays.xml
- EngineDriver/src/main/res/values-pt/arrays.xml
- EngineDriver/src/main/res/values/arrays.xml
- EngineDriver/src/main/res/values/strings.xml
+ Additional option for the Consist Follow Function feature
+ bug fix in the Consist Follow Function feature
+ support for uppercase MAC addresses for DCC-EX ESP32
Additional option for the Consist Follow Function feature
- Special Partial Contains Only - Activated if the roster function label CONTAINS Default Label
Added because the existing 'Partial' option is a bidirectional contains check.  The new option is only one direction.
> Additional option for the Consist Follow Function feature

- EngineDriver/src/main/java/jmri/enginedriver/util/comm_thread.java
1. The Consist Light editing for DCC-EX did not work
2. When the functions of a non-lead loco were received from CS, the button states for the overall consist could change (they should not)
> Bug Fixs for Functions in Consists for DCC-EX

- EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
- EngineDriver/src/main/java/jmri/enginedriver/util/comm_thread.java
when acquiring a consist where the trailing loco is reversed, the throttle control for the consist would behave reversed initially.
> Resolve problem DCC-EX native mode (only)

- EngineDriver/src/main/assets/about_page.html
- EngineDriver/src/main/java/jmri/enginedriver/ConsistEdit.java
- EngineDriver/src/main/java/jmri/enginedriver/SettingsActivity.java
- EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
- EngineDriver/src/main/java/jmri/enginedriver/select_loco.java
- EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
- EngineDriver/src/main/java/jmri/enginedriver/util/comm_handler.java
- EngineDriver/src/main/res/values/arrays.xml
- EngineDriver/src/main/res/values/bool.xml
- EngineDriver/src/main/res/values/strings.xml
- EngineDriver/src/main/res/xml/preferences.xml
- changelog-and-todo-list.txt
Enabling the new preference hides a number of purely instructional/help toast messages.  
It does not hide any error messages or many other important messages.
> Added preference to hide Instructional/Help toast popups

- EngineDriver/src/main/AndroidManifest.xml
- EngineDriver/src/main/res/values/bool.xml
Reinstate mipmap icon - needed for older version of Android
Change the owner filter preference to false
> reinstate mipmap icon

- EngineDriver/src/main/java/jmri/enginedriver/comms/comm_thread.java
- EngineDriver/src/main/java/jmri/enginedriver/withrottle_cv_programmer.java
Programming on Main requires the DCC message to be sent twice in succession. the D1 command only sends the message once (repeat count 0 when tested via Loconet).  Changing to D2 sets the repeat count to 1.
The CV itself is 0-Base in the DCC Message, but 1-base in documents and the UI.  Changed to send (CV-1) in the DCC Message.
> PoM add repeat and convert CV to base 0

- EngineDriver/src/main/assets/about_page.html
- EngineDriver/src/main/java/jmri/enginedriver/comms/comm_thread.java
- EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
- EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
- EngineDriver/src/main/res/values/bool.xml
- EngineDriver/src/main/res/values/strings.xml
- EngineDriver/src/main/res/xml/preferences.xml
- changelog-and-todo-list.txt
new preference to optional include any server with port 2560 as a DCC-EX server when the connection preference is set to 'Auto'
> new preference to optionally include any server with port 2560 as a DCC-EX server

- EngineDriver/src/main/assets/about_page.html
- EngineDriver/src/main/java/jmri/enginedriver/comms/comm_handler.java
- EngineDriver/src/main/java/jmri/enginedriver/comms/comm_thread.java
- EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
- EngineDriver/src/main/java/jmri/enginedriver/import_export/ImportExportConnectionList.java
- EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
- EngineDriver/src/main/res/values/bool.xml
- EngineDriver/src/main/res/values/strings.xml
- EngineDriver/src/main/res/xml/preferences.xml
- changelog-and-todo-list.txt
- Now also checks for the mDNSservice "_dccppovertcpserver._tcp.local."
- Now Always includes any server with port 2560 as a DCC-EX server - when the connection preference is set to 'Auto'
> - Support for JMRI DCCppOverTCP Server. 

- EngineDriver/src/main/res/layout/connection.xml
- EngineDriver/src/main/res/values/arrays.xml
- EngineDriver/src/main/res/values/bool.xml
- "Allow CV Programming On Main" defaults to "No". 
- "Connection Protocol" option changed to "WiThrottle", "DCC-EX", "Auto"
> Allow CV Programming On Main defaults to "No"

- EngineDriver/src/main/AndroidManifest.xml
- EngineDriver/src/main/java/jmri/enginedriver/comms/comm_thread.java
- EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
- EngineDriver/src/main/java/jmri/enginedriver/throttle.java
- EngineDriver/src/main/res/values/colors.xml
- automatically reduce the font size of buttons if the first word is long or the total text length is long
- more code cleanup
- up the limit for the deviceID to 999999
- Force getting a new ID when the intro is run (which is also run on a reset)
- Save the current ID and restore it when import the preferences
- split the TTS code and types into their own classes
- Added the DCC-EX toolbar button the the Routes and Turnouts/Points screens
- General cleanup and linting of the dcc_ex code
- Visual improvements to the 'about' message on the About screen and log
> deal with longInt being sent by the devel versions of DCC-EX

- EngineDriver/src/main/java/jmri/enginedriver/comms/comm_thread.java
- EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
- changelog-and-todo-list.txt
- Address anomaly where JMRI sends the DCC-EX turnouts/points before they are actually requested
> JMRI sends the DCC-EX turnouts/points before they are requested

- EngineDriver/src/main/java/jmri/enginedriver/comms/comm_handler.java
- EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
- EngineDriver/src/main/java/jmri/enginedriver/util/PermissionsHelper.java
- EngineDriver/src/main/res/values-ca/strings.xml
- EngineDriver/src/main/res/values-cs/strings.xml
- EngineDriver/src/main/res/values-de/strings.xml
- EngineDriver/src/main/res/values-es/strings.xml
- EngineDriver/src/main/res/values-fr-rCA/strings.xml
- EngineDriver/src/main/res/values-fr/strings.xml
- EngineDriver/src/main/res/values-it/strings.xml
- EngineDriver/src/main/res/values-ja/strings.xml
- EngineDriver/src/main/res/values-pt/strings.xml
- EngineDriver/src/main/res/values/strings.xml
- changelog-and-todo-list.txt
Previously it failed gracefully if the permission was not granted, but was not clear that the stop on phone call would not work.
Now it asks a couple of times before deliberately disabling the stop on phone call preference.
> Make the PHONE permission more obviously 'optional'

- EngineDriver/src/main/java/jmri/enginedriver/comms/comm_thread.java
- EngineDriver/src/main/java/jmri/enginedriver/connection_activity.java
- EngineDriver/src/main/java/jmri/enginedriver/intro/intro_activity.java
- EngineDriver/src/main/java/jmri/enginedriver/intro/intro_finish.java
- EngineDriver/src/main/java/jmri/enginedriver/threaded_application.java
- EngineDriver/src/main/java/jmri/enginedriver/util/PermissionsHelper.java
- EngineDriver/src/main/res/values-ca/strings.xml
- EngineDriver/src/main/res/values-cs/strings.xml
- EngineDriver/src/main/res/values-de/strings.xml
- EngineDriver/src/main/res/values-es/strings.xml
- EngineDriver/src/main/res/values-fr/strings.xml
- EngineDriver/src/main/res/values-it/strings.xml
- EngineDriver/src/main/res/values-ja/strings.xml
- EngineDriver/src/main/res/values-pt/strings.xml
- EngineDriver/src/main/res/values/strings.xml
- changelog-and-todo-list.txt
- location permission denied only shows a toast message now on the connection screen
- AppIntro disables the "Phone call" permission on the last page if PHONE permission not granted  
- Fixed the "Write System" permissions page in AppIntro  (was using the wrong layout)
> Tidy up of the AppIntro permissions

- EngineDriver/src/main/java/jmri/enginedriver/web_activity.java
- changelog-and-todo-list.txt
Bug Fix - If you try to close the Web screen if using anything other than the default throttle layout, ED will crash.
> - Bug Fix - If you try to close the Web screen
